### PR TITLE
fix regexp in DefaultStatsPrinterPlugin.js

### LINKED ISSUE #14678: Performance issue with DefaultStatsPrinterPlugin.js
# Bug report

**What is the current behavior?**

DefaultStatsPrinterPlugin.js is slow to process/display results when large error message is returned.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction in repo: https://github.com/martinsp/webpack-printer-issue running `npx webpack` will take significant amount of time

I have narrowed the issue down to this line: https://github.com/webpack/webpack/blob/14dd4f912c013f060bf7843a3d5462a51ff3051b/lib/stats/DefaultStatsPrinterPlugin.js#L1163 when it's commented out then the webpack command completes within a short amount of time

**What is the expected behavior?**

webpack results shown in a short amount of time

**Other relevant information:**
webpack version:  5.62.1
Node.js version: v17.0.1
Operating System: macOS Monterey
Additional tools:

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

bugfix

fixes #14678 

**Did you add tests for your changes?**

no

**Does this PR introduce a breaking change?**

nothing

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

File: lib/stats/DefaultStatsPrinterPlugin.js [hunk 1]
```diff
@@ -1160,7 +1160,7 @@ const AVAILABLE_FORMATS = {
 			},
 			{ regExp: /(\(module has no exports\))/g, format: red },
 			{ regExp: /\(possible exports: (.+)\)/g, format: green },
-			{ regExp: /\s*(.+ doesn't exist)/g, format: red },
+			{ regExp: /\s*([^\s].* doesn't exist)/g, format: red },
```
Comment (alexander-akait) [inline lib/stats/DefaultStatsPrinterPlugin.js:1163]: @vankop make sense to look at other `.+` places

Comment (alexander-akait) [reply lib/stats/DefaultStatsPrinterPlugin.js:1163]: Also small test to avoid regressions

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
