### PR TITLE
Fix module concatenation renaming bug

### LINKED ISSUE #12712: Module concatenation bug in destructuring assignment with default value
# Bug report

**What is the current behavior?**

When using destructuring assignment in a module, in combination with a default assignment, it can cause the property looked up in the generated code to be different than the one in the source code _(it uses `newName`)_ if there's a identifier collision.

```js
// index.js
import modA from "./module-a";
import modB from "./config";

const { testProp = "defaultValue" } = modB;

modA();
console.log(testProp);
```
```js
// module-a.js

// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

export default function printModuleAProp() {
  console.log(testProp);
}
```
```js
// config.js
export default {
  testProp: "configuredValue",
};
```

Generated code:

```js

/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};

;// CONCATENATED MODULE: ./src/module-a.js
// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

function printModuleAProp() {
  console.log(testProp);
}

;// CONCATENATED MODULE: ./src/config.js
/* harmony default export */ const config = ({
	testProp: "configuredValue",
});

;// CONCATENATED MODULE: ./src/index.js



const { src_testProp = "defaultValue" } = config;

printModuleAProp();
console.log(src_testProp);

/******/ })()
;
```

The incorrect part is this line:

```js
const { src_testProp = "defaultValue" } = config;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/PAkerstrand/webpack-concatenation-bug

**What is the expected behavior?**

The generated line should be along the lines of 

```js
const { testProp: src_testProp = "defaultValue" } = config;
```

We think we've narrowed down the bug to this part in `lib/optimize/ConcatenatedModule.js`:

```js
for (const identifier of allIdentifiers) {
	const r = identifier.range;
	const path = getPathInAst(info.ast, identifier);
	if (
		path &&
		path.length > 1 &&
		path[1].type === "Property" &&
		path[1].shorthand
	) {
		source.insert(r[1], `: ${newName}`);
	} else {
		source.replace(r[0], r[1] - 1, newName);
	}
}
```

For the code in our example, the path taken is the `else`-branch, which replaces the name with a new
one, rather than aliasing the variable name

**Other relevant information:**
webpack version:  `^5.22.0`
Node.js version: `v14.15.4`
Operating System: 
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
```
Additional tools: –

### PR DESCRIPTION
**Pull request by PAkerstrand**
## Background

When using destructuring assignment in a module, in combination with a default assignment, it can cause the property looked up in the generated code to be different than the one in the source code _(it uses `newName`)_ if there's a identifier collision.

```js
// index.js
import modA from "./module-a";
import modB from "./config";

const { testProp = "defaultValue" } = modB;

modA();
console.log(testProp);
```
```js
// module-a.js

// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

export default function printModuleAProp() {
  console.log(testProp);
}
```
```js
// config.js
export default {
  testProp: "configuredValue",
};
```

Generated code:

```js

/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};

;// CONCATENATED MODULE: ./src/module-a.js
// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

function printModuleAProp() {
  console.log(testProp);
}

;// CONCATENATED MODULE: ./src/config.js
/* harmony default export */ const config = ({
	testProp: "configuredValue",
});

;// CONCATENATED MODULE: ./src/index.js



const { src_testProp = "defaultValue" } = config;

printModuleAProp();
console.log(src_testProp);

/******/ })()
;
```

## Analysis

If the code looks like in the following picture
image

we get a AST tree with paths that look like this:
ConcatenatedModule_js_—_concatenate-bug

In this case, the `Property` we want to change is at index `1`, which the code handles just fine.

However, the bug appears when you've got code that looks like this:
image

In that case, you get an AST that looks like the following:
ConcatenatedModule_js_—_concatenate-bug

In this case, the code generator will take the second branch inside of `lib/optimize/ConcatenatedModule.js`, and change the name of the property without aliasing it, causing the semantics to change. The reason for that is that we have an `AssignmentPattern` at index `1`, while the `Property` we want to change is now at index `2`.

## The fix

This PR simply adds an additional check for this condition, and creates output like this instead:

```diff
- const { src_testProp = "defaultValue" } = config;
+ const { testProp: src_testProp = "defaultValue" } = config;
```

Closes #12712 

**What kind of change does this PR introduce?**

bugfix

**Did you add tests for your changes?**

Yes

**Does this PR introduce a breaking change?**

No

**What needs to be documented once your changes are merged?**

None, this is expected behaviour

### CODE REVIEW

**Comment by PAkerstrand** [comment]
I'm not sure how to get this test to pass? 
image

I've clicked the details, and signed the CLA. If/when I visit it now everything is "inactive" and immutable, saying that I've signed it already
image

**Comment by alexander-akait** [comment]
Sometimes bot is freeze, close/open helps

File: lib/optimize/ConcatenatedModule.js [hunk 1]
```diff
@@ -1246,6 +1246,14 @@ class ConcatenatedModule extends Module {
 									path[1].shorthand
 								) {
 									source.insert(r[1], `: ${newName}`);
+								} else if (
+									path &&
+									path.length &&
+									path[1].type === "AssignmentPattern" &&
+									path[2].type === "Property" &&
+									path[2].shorthand
+								) {
```
Comment (sokra) [inline lib/optimize/ConcatenatedModule.js:1255]: let's make it a bit shorter

``` js
if (path && path.length > 1) {
    const maybeProperty = path[1].type === "AssignmentPattern" ? path[2] : path[1];
    if (maybeProperty.type === "Property" && maybeProperty.shorthand) {
        source.insert(r[1], `: ${newName}`);
        continue;
    }
}
source.replace(r[0], r[1] - 1, newName);
```

**Review by sokra — CHANGES_REQUESTED** [review]

**Comment by sokra** [comment]
Thanks
