### PR TITLE
hash content of bootstrap code

### LINKED ISSUE #7984: contenthash changing even though file remains identical
# Bug report

```js
	output: {
		filename: 'file-[contenthash].js',
		chunkFilename: 'chunk-[contenthash].js'
	},
        optimization: {
        	splitChunks: {
		chunks: 'all',
		cacheGroups: {
				vendors: {
					test: /[\\/]node_modules[\\/]/,
				},
			},
		},
       }
```

**What is the current behavior?**

If I have the above config, in my build I get a file called `file-XXX.js` and `chunk-XXX.js`. If I change the config line from `chunkFilename: 'chunk-[contenthash].js'` to `chunkFilename: 'CHUNK-[contenthash].js'`, then the files are `file-YYY.js` and `chunk-XXX.js`. So `chunk-` has the same name but `file-` has a different name when the `chunkFilename` changes.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a webpack bundle when the chunkFilename is set to one value, then create another bundle after changing the chunkFilename. You'll see the the contenthash has changed even though the file contents are identical.

**What is the expected behavior?**

I'm using `[contenthash]` and in both cases the file contents are identical so the contenthash shouldn't change and the filename should remain the same.

**Other relevant information:**
webpack version:  4.17.1
Node.js version: 10.9.0
Operating System: linux 
Additional tools:

### LINKED ISSUE #8027: Same chunkhash for different output
# Bug report

**What is the current behavior?**

Our current config is:
```js
module.exports = {
    mode: 'production',
    entry: {
        'babel-stuff': [
            './var/www/s/babel-external-helpers.js',
            'babel-polyfill'
        ]
        // ... many other entrypoints
    },
    output: {
        path: 'some path to output',
        publicPath: '/s/cc/',
        filename: 'bundles/[chunkhash].js',
        chunkFilename: 'chunks/[chunkhash].js'
    },
    devtool: false,
    plugins: [
      // extract css
    ],
    optimization: {
        splitChunks: {
            maxInitialRequests: 10,
            maxAsyncRequests: 10,
            chunks: 'all',
            // disable css-splitting till fix the bug in mini-css-extract-plugin
            cacheGroups: {
                vendors: {
                    test: /\/node_modules\/.+\.js$/,
                    priority: -10
                },
                default: {
                    test: /\.js$/,
                    minChunks: 2,
                    priority: -20,
                    reuseExistingChunk: true
                }
            }
        },
        module: {
            noParse: [
                // some regexps
            ],
            rules: [
                {
                    test: /\.js$/,
                    use: [
                        {
                            loader: 'babel-loader',
                            options: {
                                cacheDirectory: 'path/to/cache'
                            }
                        }
                    ]
                },
                // other loaders for styl/css/svg/etc... 
            ]
        }
    };
```

And we got the same `chunkshash` `03ac84533a4d9ba84a13` for different file content on the output directory.

```diff
diff path/to/good/03ac84533a4d9ba84a13.js path/to/bad/03ac84533a4d9ba84a13.js -U 10
--- path/to/good/03ac84533a4d9ba84a13.js     2018-09-13 18:41:47.000000000 +0300
+++ path/to/bad/03ac84533a4d9ba84a13.js      2018-09-13 18:41:47.000000000 +0300
@@ -65,21 +65,21 @@
         return u.d(r, "a", r), r
     }, u.o = function(e, r) {
         return Object.prototype.hasOwnProperty.call(e, r)
     }, u.p = "/s/cc/";
     var a = window.webpackJsonp = window.webpackJsonp || [], f = a.push.bind(a);
     a.push = r, a = a.slice();
     for (var l = 0; l < a.length; l++) {
         r(a[l]);
     }
     var c = f;
-    i.push([2729, 847]), t()
+    i.push([2729, 849]), t()
 }({
     2729: function(e, r, t) {
         t(2730), e.exports = t(2731)
     }, 2730: function(e, r) {
         (function() {
             void 0, function(e) {
                 var r = e.babelHelpers = {};
                 r.typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function(e) {
                     return typeof e
                 } : function(e) {

```

Because of it, long term caching is not working correctly...

**If the current behavior is a bug, please provide the steps to reproduce.**

Not sure how to reproduce exactly this 
behavior...
We just modified our code base inside other entry points (not in `babel-stuff`) and got the different content in the output file of babel-stuff asset, but the same hash for it.

**What is the expected behavior?**
- Different chunkhash for different output
- Same output content for entry points that were not changed (e.g. babel-stuff)

**Other relevant information:**
webpack version:  4.17.2
Node.js version: 8.11.4
Operating System: MacOS 10.12.6
Additional tools:

### PR DESCRIPTION
**Pull request by sokra**
instead of trying to calculate it
from inputs

fixes #8027
fixes #7984

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
existing tests

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/ChunkTemplate.js [hunk 1]
```diff
@@ -71,12 +72,15 @@ module.exports = class ChunkTemplate extends Tapable {
...
+	 * TODO webpack 5: remove moduleTemplate and dependencyTemplates
 	 * Updates hash with chunk-specific information from this template
 	 * @param {Hash} hash the hash to update
 	 * @param {Chunk} chunk the chunk
+	 * @param {ModuleTemplate} moduleTemplate ModuleTemplate instance for render
+	 * @param {Map<Function, DependencyTemplate>} dependencyTemplates dependency templates
 	 * @returns {void}
 	 */
-	updateHashForChunk(hash, chunk) {
+	updateHashForChunk(hash, chunk, moduleTemplate, dependencyTemplates) {
```
Comment (smelukov) [inline lib/ChunkTemplate.js]: seems like `moduleTemplate` and `dependencyTemplates` is unused...
