### PR TITLE
fix: meta property hook rework

### LINKED ISSUE #11310: [Webpack 5] "new.target" is replaced by "Object()"
# Bug report

**What is the current behavior?**
Webpack replace "new.target" by "Object()" which cause error.

**If the current behavior is a bug, please provide the steps to reproduce.**

> index.ts
```typescript
class A {
	static get instance() {
		return Reflect.construct(A, [], B);
	}
	
	constructor() {
		if (new.target != B) {
			throw new Error();
		}
	}
}

class B extends A {}

console.log(A.instance);
```

> tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "commonjs",
    "strict": true
  }
}
```

```
> npx webpack index.ts --output dist.js
```

------------------------------

TypeScript is transpiled right:
```javascript
"use strict";
class A {
    static get instance() {
        return Reflect.construct(A, [], B);
    }
    constructor() {
        if (new.target != B) {
            throw new Error();
        }
    }
}
class B extends A {
}
console.log(A.instance);
```

But output of dist.js is:
```javascript
(() => {
    class t {
        static get instance() {
            return Reflect.construct(t, [], c)
        }

        constructor() {
            if (Object() != c) throw new Error // THIS IS THE BUG!
        }
    }

    class c extends t {
    }

    console.log(t.instance)
})();
```

**What is the expected behavior?**
"new.target" should be leaved as is. 

**Other relevant information:**
Node.js version: 14.4
Operating System: Win 10
```json
  "dependencies": {
    "typescript": "^3.9.7",
    "webpack": "^5.0.0-beta.25"
  },
  "devDependencies": {
    "webpack-cli": "^3.3.12"
  }
```

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

bugfix
fixes #11310 

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

File: lib/dependencies/ImportMetaPlugin.js [hunk 1]
```diff
@@ -56,26 +56,27 @@ class ImportMetaPlugin {
...
-								),
-								metaProperty.loc
-							)
-						);
-						const dep = new ConstDependency("Object()", metaProperty.range);
-						dep.loc = metaProperty.loc;
-						parser.state.module.addPresentationalDependency(dep);
-						return true;
-					});
+					parser.hooks.metaProperty
```
Comment (sokra) [inline lib/dependencies/ImportMetaPlugin.js:59]: Do we even need a separate hooks for that or could we just use the `expression` hook?

File: lib/javascript/JavascriptParser.js [hunk 2]
```diff
@@ -2657,7 +2657,7 @@ class JavascriptParser extends Parser {
 	 * @param {MetaPropertyNode} metaProperty meta property
 	 */
 	walkMetaProperty(metaProperty) {
-		this.hooks.metaProperty.call(metaProperty);
+		this.hooks.metaProperty.for(getRootName(metaProperty)).call(metaProperty);
```
Comment (sokra) [inline lib/javascript/JavascriptParser.js:2660]: Do we even need a separate hooks for that or could we just use the `expression` hook?

File: lib/dependencies/ImportMetaPlugin.js (hunk 1 above)
Comment (vankop) [reply lib/dependencies/ImportMetaPlugin.js:59]: When I was doing this I also thought about it, I think it is about 2 things here:
1. perf - algorithm complexity is the same.
2. DX - I think for DX it is better to have separate hook since `MetaProperty` !== `Expression`

**Comment by sokra** [comment]
Thanks
