### PR TITLE
fix(stats): allow stats to respect array of configs, also bump deps.

### LINKED ISSUE #3512: cannot use 'stats' config presets when exporting an array of configs
**Do you want to request a *feature* or report a *bug*?**
bug report

**What is the current behavior?**
builds fail because the 'stats' config is expecting an object when I pass it a preset as a string

**What is the expected behavior?**
as the [documentation](https://webpack.js.org/configuration/stats/#stats) says, presets should be allowed. The website is documenting 2.1, but I'm assuming this is also the expected behaviour for 2.2?

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Node 7.2.1, Ubuntu 16.10, Webpack 2.2rc1

### PR DESCRIPTION
**Pull request by TheLarkInn**
**What kind of change does this PR introduce?**
Bugfix

**Did you add tests for your changes?**
Yes

**If relevant, link to documentation update:**

**Summary**

Fixes #3512

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

File: bin/webpack.js [hunk 1]
```diff
@@ -160,11 +169,20 @@ function processOptions(options) {
 		return;
 	}
 
+	// var firstOptions = Array.isArray(options) ? (options[0] || {}) : options;
```
Comment (sokra) [inline bin/webpack.js]: remove

File: bin/webpack.js [hunk 2]
```diff
@@ -160,11 +169,20 @@ function processOptions(options) {
...
 	var firstOptions = Array.isArray(options) ? (options[0] || {}) : options;
-
-	if(typeof options.stats === "boolean" || typeof options.stats === "string") {
+	if(hasPreset(options)) {
 		var statsPresetToOptions = require("../lib/Stats.js").presetToOptions;
-		options.stats = statsPresetToOptions(options.stats);
+
+		if(Array.isArray(options)) {
+
+			options = options.map(function(singleOption) {
```
Comment (sokra) [inline bin/webpack.js]: a forEach could do the same job.

File: bin/webpack.js [hunk 3]
```diff
@@ -160,11 +169,20 @@ function processOptions(options) {
...
+				singleOption.stats = statsPresetToOptions(singleOption.stats);
+				return singleOption;
+			})
```
Comment (sokra) [inline bin/webpack.js]: `;` missing, but i wonder why this is not catched by the linting...

File: bin/webpack.js [hunk 4]
```diff
@@ -161,10 +170,16 @@ function processOptions(options) {
...
+		if(Array.isArray(options)) {
+			options = options.forEach(function(singleOption) {
+				singleOption.stats = statsPresetToOptions(singleOption.stats);
+			});
+		} else {
+			options.stats = statsPresetToOptions(options.stats);
+		}
 	}
 
 	var outputOptions = Object.create(options.stats || firstOptions.stats || {});
```
Comment (sokra) [inline bin/webpack.js]: Could this superseed the above code?

```
var outputOptions = Object.create(statsPresetToOptions(options.stats || firstOptions.stats || {}));
```

Comment (TheLarkInn) [inline bin/webpack.js]: If that function can take an array of options, probably.

Comment (TheLarkInn) [inline bin/webpack.js]: Only problem I see with that is that `Stats.presetToOptions` is really for just taking a string and converting it. I could add the array handling case but that could technically negate the truthyness of passing an empty array to `stats: []`. 

If we took it that far I could check to see if the array had a length to it to determine if it was actually an array of configs with stats strings inside, but feels like a lot of unneeded logic. 

I could maybe see creating a `Stats.optionsArrayWithStatsPresetToOptionsArray`. It would probably just iterate over the array and call `Stats.statsToOptions` on `options.stats`.

Comment (TheLarkInn) [inline bin/webpack.js]: Or if you are looking to not have the logic in `webpack.js`:

```js
		if(Array.isArray(options)) {
			options = options.forEach(function(singleOption) {
				singleOption.stats = statsPresetToOptions(singleOption.stats);
			});
		} else {
			options.stats = statsPresetToOptions(options.stats);
		}
```
I think this much enough could be extracted and put into `Stats.js` as a static/object method.

**Comment by sokra** [comment]
hmm. I think we have a bigger problem with stats for multiple compilations. The current approach and the current stats only allow a single stats options object, but you probably want different options per compilations:

``` js
[
 { ..., stats: "none" },
 { ..., stats: "verbose" }
]
```

But the current archtiture doesn't support this.

Could you split the unrelated changes into a separate PR so we could merge these at least?

**Comment by TheLarkInn** [comment]
Merge the version bump changes or merge these changes.

**Comment by TheLarkInn** [comment]
@sokra Once #3643 merges, I'll update this PR to have a couple tests covering array cases.

File: bin/webpack.js [hunk 5]
```diff
@@ -161,6 +161,15 @@ function ifArg(name, fn, init) {
 	}
 }
 
+function hasPresetPredicate(options) {
+	return typeof options.stats === "boolean" || typeof options.stats === "string";
+}
+
+function hasPreset(optionsArray) {
+	options = Array.isArray(optionsArray) ? optionsArray : [optionsArray];
```
Comment (Kovensky) [inline bin/webpack.js]: Hm... `[].concat(optionsArray)`? Too magic?
