### PR TITLE
fix: handle class name in properties and methods

### LINKED ISSUE #16262: incorrect "unused pure expression or super"
# Bug report

**What is the current behavior?**

Code like this,

```js
let _Foo;

class Foo {
  static #_ = [_init_foo, _initProto, _Foo, _initClass2] = _applyDecs(this, [[signal, 3, "lorem"], [signal, 0, "foo"]], [reactive]);
  foo = (_initProto(this), _init_foo(this, 123));

  get lorem() {
    return 123;
  }

  set lorem(v) {
    v;
  }

  static #_2 = _initClass2();
}

let _Bar;

class Bar extends _Foo {
  static #_ = [_init_bar, _initProto2, _Bar, _initClass3] = _applyDecs(this, [[signal, 3, "baz"], [signal, 0, "bar"]], [reactive]);
  bar = (_initProto2(this), _init_bar(this, 456));
  #baz = 789;

  get baz() {
    return this.#baz;
  }

  set baz(v) {
    this.#baz = v;
  }

  constructor() {
    super();
    console.log('Bar');
  }

  static #_2 = _initClass3();
}
```

turns into code like this,

```js
let _Foo;

class Foo {
  static #_ = [_init_foo, _initProto, _Foo, _initClass2] = _applyDecs(this, [[signal, 3, "lorem"], [signal, 0, "foo"]], [reactive]);
  foo = (_initProto(this), _init_foo(this, 123));

  get lorem() {
    return 123;
  }

  set lorem(v) {
    v;
  }

  static #_2 = _initClass2();
}

let _Bar;

class Bar extends (/* unused pure expression or super */ null && (_Foo)) {
  static #_ = [_init_bar, _initProto2, _Bar, _initClass3] = _applyDecs(this, [[signal, 3, "baz"], [signal, 0, "bar"]], [reactive]);
  bar = (_initProto2(this), _init_bar(this, 456));
  #baz = 789;

  get baz() {
    return this.#baz;
  }

  set baz(v) {
    this.#baz = v;
  }

  constructor() {
    super();
    console.log('Bar');
  }

  static #_2 = _initClass3();
}
```

and the class fails to run because `super()` tries to call `null`.

The input is output from Babel's new Stage 3 decorators. The `static #_` initializer runs code that sets up the `_Foo` variable.

**If the current behavior is a bug, please provide the steps to reproduce.**

I haven't published a reproduction yet.

**What is the expected behavior?**

**Other relevant information:**
webpack: 5.74.0

### LINKED ISSUE #16330: Error when compiling typescript in target es2022
# Bug report

**What is the current behavior?**
Error when compiling typescript in target es2022

**If the current behavior is a bug, please provide the steps to reproduce.**
tsconfig.json
```
{
   ...
   "compilerOptions" {
       ...
       "target": "ES2022",
       ...
   }
    ...
}
```
module1.ts
```
export let userId = document.body.getAttribute("data-user-id")!
```
module2.ts
```
import { userId } from "./module1"; 

export class Theme {
    private constructor() {}
    private static Change(isCallback: boolean) {
        localStorage.removeItem('lightTheme_'+userId)
    }
    static {
        localStorage.getItem('lightTheme_'+userId) && this.Change(false)
    }
}
```
Compiling produces the following file:
```
...
;// CONCATENATED MODULE: ../ts/module1.ts
let module1_userId = document.body.getAttribute("data-user-id");

;// CONCATENATED MODULE: ../ts/module2.ts

class Theme {
    constructor() { }
    static Change(isCallback) {
        localStorage.removeItem('lightTheme_' + userId);
    }
    static {
        localStorage.getItem('lightTheme_' + module1_userId) && this.Change(false);
    }
}
...
```
the userId that is in the static block is renamed to module1_userId, and the userId that is in the Change function is not renamed

if you remove static, then all the same, userId will not be renamed inside the class.
In the global context it is renamed normally

**What is the expected behavior?**
userId must not be renamed to module1_userId. At least this behavior is observed with target = es2021

**Other relevant information:**
webpack version:   5.74.0
webpack cli version: 4.10.0
Node.js version:  14.19.0
Operating System:  Mac Os Mojave 10.14.6
Additional tools:

### LINKED ISSUE #16763: Reference to class name in body of class expression is replaced with reference to import when class name shadows import name
# Bug report

**What is the current behavior?**

The calls to static members of the class fail inside the class body when the name of the class in a class expression shadow a import name.

**If the current behavior is a bug, please provide the steps to reproduce.**

a.mjs:

```js
export const a = 1;
```

index.mjs:

```js
import { a as C } from "./a.mjs"

let CV = class C {
  static name = "test";
  static test() {
    console.log(C.name);
  }
}

console.log(C);
CV.test();
```

Bundled code snippet in `none` mode:

```js
let CV = class C {
  static name = "test";
  static test() {
    console.log(_a_mjs__WEBPACK_IMPORTED_MODULE_0__.a.name);
  }
}

console.log(_a_mjs__WEBPACK_IMPORTED_MODULE_0__.a);
CV.test();

})();
```

Bundled code in `production` mode:

```js
(()=>{"use strict";console.log(1),class{static name="test";static test(){console.log(1..name)}}.test()})();
```

Running dist output in either mode:

```console
> node dist/index.js
1
undefined
```

**What is the expected behavior?**

Running src code:

```console
> node src/index.mjs
1
test
```

**Other relevant information:**
webpack version: 5.75.0
Node.js version: 19.7.0
Operating System: 
Additional tools:

This code pattern came about as a result of the changes in Rollup PR https://github.com/rollup/rollup/pull/4827 and how Terser will shadow the import when possible when mangling.

### LINKED ISSUE #17239: Class A cannot instantiate an object B that inherit from A
# Bug report

**What is the current behavior?**

I try to write a class `A` that instantiate an object `B` that inherit from `A`?

I get the following error on runtime
```
a.js:3 Uncaught ReferenceError: Cannot access 'A' before initialization
    at Module.default (a.js:3:56)
    at eval (b.js:3:32)
    at ./src/js/b.js (bundle.425598c….js:723:1)
    at __webpack_require__ (bundle.425598c….js:1278:41)
    at eval (a.js:5:63)
    at ./src/js/a.js (bundle.425598c….js:712:1)
    at __webpack_require__ (bundle.425598c….js:1278:41)
    at eval (index.js:2:63)
    at ./src/js/index.js (bundle.425598c….js:821:1)
    at __webpack_require__ (bundle.425598c….js:1278:41)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

I use 3 files:
# index.js
```
import A from "./a.js";
let a = new A();
a.fct();
```

# a.js

```
import B from "./b.js"
    
export default class A {
  constructor() {
    console.log ("a constructor")
  }
  fct() {
    this.b = new B();
  }
}
```

# b.js 

```
import A from "./a.js"
    
export default class B extends A {
  constructor() {
    console.log ("b constructor")
  }
}
```

**What is the expected behavior?**

It shouldn't trigger an error at runtime. Since this is technically possible in JS as prooven on this [JSFiddle](https://jsfiddle.net/Imabot/x4fjav5L/)

**Other relevant information:**
webpack version:  5.82.0
Node.js version: 18.16.0
Operating System: Ubuntu 22.04
Additional tools: -

### PR DESCRIPTION
**Pull request by alexander-akait**
fixes #16763
fixes #16330
fixes #16262
fixes #17239

### <samp>🤖 Generated by Copilot at 0a2cef7</samp>

Fix scope bug for recursive class methods by wrapping class body in a function. Add support for static blocks in classes.

### <samp>🤖 Generated by Copilot at 0a2cef7</samp>

* Fix scope bug for recursive class methods by wrapping class body loop in a function scope and passing class name as a parameter if it exists ([link](https://github.com/webpack/webpack/pull/17233/files?diff=unified&w=0#diff-561daa0feb66d49c350f9f8296e8f9bfe50a7ed5efbb4226d2b512aa20d201f2L1564-R1596))

### CODE REVIEW

**Review by hexiaokang — APPROVED** [review]

File: test/cases/inner-graph/extend-class/dep3.js [hunk 1]
```diff
@@ -12,7 +12,7 @@ export const C1 = class C1 extends mixin2(Y, /*#__PURE__*/ mixin3(C)) {
 	render() {return new D();}
 };
 
-export class Y1 extends mixin2(Y) {
+export class Y1 extends /*#__PURE__*/ mixin2(Y) {
```
Comment (alexander-akait) [inline test/cases/inner-graph/extend-class/dep3.js:15]: We use `mixin1` inside this class, so we can't drop it, because `mixin2` is not `pure`, sounds like we have a bug before

**Review by TheLarkInn — APPROVED** [review]

**Comment by TheLarkInn** [comment]
@alexander-akait Sorry I think I'm merging things out of order can you rebase this?

**Comment by alexander-akait** [comment]
@TheLarkInn Yeah, will do soon :+1:

**Comment by alexander-akait** [comment]
@TheLarkInn Done :+1:
