### PR TITLE
fix(require.ensure): add ArrowFunctionExpression support: Fixes #959

### LINKED ISSUE #959: Uncaught TypeError: Cannot read property 'call' of undefined
I'm having an issue with webpack where if I stop watching and restart, it will build just fine, but if I edit a file and save it, the incremental build fails with this error:

**Uncaught TypeError: Cannot read property 'call' of undefined**

Hunting it down there's a module that does not get included in the incremental change build. Best guess is the path followed to re-make the bundle file is not being followed correctly. Upon re-running (stop and start), the missing module is included.

webpack.config.js (module names changed to protect the innocent):

``` javascript
var webpack = require("webpack"),
    path = require('path')
    ;

module.exports = {
  entry: {
    Entry1: "./app/Entry1.js",
    Entry2: "./app/Entry2.js",
    Entry3: "./app/Entry3.js",
    Entry4: "./app/Entry4.js",
    Entry5: "./app/Entry5.js",
    Entry6: "./app/Entry6.js",
    Entry7: "./app/Entry7.js",
    Entry8: "./app/Entry8.js",
  },
  output: {
    path: path.join(__dirname, "public/js"),
    filename: "[name].bundle.js",
    chunkFilename: "[id].chunk.js"
  },
  module: {
    loaders: [
      {test: /\.js$/, loader: 'jsx-loader'}
    ]
  },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin("shared.js")
    ]
};
```

### PR DESCRIPTION
**Pull request by TheLarkInn**
**What kind of change does this PR introduce?**
Bugfix. Fixes #959 

* `require.ensure` was erroring when passing arrow function as callback. 
* bumped uglify-js patch level deps
* add node target cases for `import()`

**Did you add tests for your changes?**
Yes 

**If relevant, link to documentation update:**
N/A

**Summary**

**Does this PR introduce a breaking change?**
No

**Other information**

### CODE REVIEW

File: test/cases/parsing/chunks/index.js [hunk 1]
```diff
@@ -19,4 +19,11 @@ it("should parse a string in require.ensure", function(done) {
 		require("./file").should.be.eql("ok");
 		done();
 	});
-});
\ No newline at end of file
+});
+
+it("should parse a string in require.ensure with arrow function expression", function(done) {
+	require.ensure("./file", require => {
```
Comment (sokra) [inline test/cases/parsing/chunks/index.js]: Could you also add a test with a single expression array function? They behave a bit different in AST.

``` js
require.ensure("./file", require => (require("./file").should.be.eql("ok"), done()))
```

**Comment by sokra** [comment]
Thanks

File: test/cases/parsing/chunks/index.js (hunk 1 above)
Comment (mantou132) [inline test/cases/parsing/chunks/index.js]: Is this just a difference in performance?
Thanks
