### PR TITLE
fixup reasons when redirecting dependencies for side-effects

### LINKED ISSUE #7428: (4.10.0) "Module has no id. This should not happen" when using dynamic import and sideEffects flag
# Bug report

**What is the current behavior?**
`RuntimeTemplate.moduleId(): Module <path>\packages\components\src\CompAB\CompA.js has no id. This should not happen.`

**If the current behavior is a bug, please provide the steps to reproduce.**
- Clone https://github.com/sqal/webpack-bug-reproduction
- `npm install && npm run build`

This error occurs only in the following situation:
- `"sideEffects: false"` is required (is set in components package.json) - if you remove it, you won't see the error
- Module is imported twice (using static import and dynamic import) - if you remove dynamic import of `./foo` from main.js or static import of `CompA` - no error

**What is the expected behavior?**
Should compile without the error

**Other relevant information:**
webpack version:  4.10.0
Node.js version: 9.6.1
Operating System: Windows 10 x64
Additional tools: -

### PR DESCRIPTION
**Pull request by sokra**
also: show reason explanation in stats

fixes #7428

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/optimize/SideEffectsFlagPlugin.js [hunk 1]
```diff
@@ -115,6 +116,15 @@ class SideEffectsFlagPlugin {
 								if (mapping) {
 									dep.redirectedModule = mapping.module;
 									dep.redirectedId = mapping.exportName;
+									module.reasons.splice(i--, 1);
```
Comment (ooflorent) [inline lib/optimize/SideEffectsFlagPlugin.js]: This is really bad for perfs. Would it be possible to build a second array or to modify `module.reasons` in a second loop?

Comment (sokra) [reply lib/optimize/SideEffectsFlagPlugin.js]: I'll do this in a separate PR. I want to fix the bug first.
