### PR TITLE
fixes #12769

### LINKED ISSUE #12769: Module concatenation produces invalid syntax when using object destructuring with a default
# Bug report

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

See reproduction: https://github.com/Hypnosphi/webpack-5-repro

Here’s the output with invalid syntax:

```js
// CONCATENATED MODULE: ./src/b.js
function b_noop() {}

function B({foo = noop: b_noop}) {}
```

**What is the expected behavior?**

```js
// CONCATENATED MODULE: ./src/b.js
function b_noop() {}

function B({foo = b_noop}) {}
```

**Other relevant information:**
webpack version:  5.24.0
Node.js version: 12.20.2
Operating System: Linux, macOS
Additional tools: no

### PR DESCRIPTION
**Pull request by sokra**
fixes #12769

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by PAkerstrand** [comment]
Cheers! Just noticed the same bug myself

File: lib/optimize/ConcatenatedModule.js [hunk 1]
```diff
@@ -1241,7 +1241,10 @@ class ConcatenatedModule extends Module {
 								const path = getPathInAst(info.ast, identifier);
 								if (path && path.length > 1) {
 									const maybeProperty =
-										path[1].type === "AssignmentPattern" ? path[2] : path[1];
+										path[1].type === "AssignmentPattern" &&
+										path[1].left === path[0]
```
Comment (PAkerstrand) [inline lib/optimize/ConcatenatedModule.js:1245]: I thought about writing this as `path[1].left === identifier`. Exactly the same thing, but perhaps the intent would be clearer?
