### PR TITLE
Compiler dependency error

### LINKED ISSUE #5414: Typo in dependencies results in a undescriptive error message
This is a bug report in webpack 3.4.1 (and webpack@beta).

**What is the current behavior?**
In the [following gist](https://gist.github.com/nemtsov/b1df26c3ed6025879590e34c399f9f2a) there are two configs, one depending on another. If you provide an incorrect dependency name, the error message is `Cannot read property 'hash' of null`, which does not describe the root cause of the issue and makes it difficult to debug.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/nemtsov/b1df26c3ed6025879590e34c399f9f2a

**What is the expected behavior?**

An error message that describes the root cause, e.g., `Undefined dependency "commonBAD" in "build/a.js"`

### PR DESCRIPTION
**Pull request by rrharvey**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**If relevant, link to documentation update:**

**Summary**
Generates a friendly error message if there are problems with compiler dependencies in a multi-config. 

Currently these throw unhelpful runtime errors. Fixes #5414

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

File: lib/MultiCompiler.js [hunk 1]
```diff
@@ -75,6 +75,51 @@ module.exports = class MultiCompiler extends Tapable {
...
+				if(!edges.find(e => e.target === target)) {
+					stack.push(target);
+				}
+			}
+		}
+		if(edges.length > 0) {
+			errors.unshift("Circular dependency found in compiler dependencies.");
+		}
+		if(errors.length > 0) {
+			callback(errors.join("\n"));
```
Comment (sokra) [inline lib/MultiCompiler.js]: This should be an `Error` object.

Comment (rrharvey) [reply lib/MultiCompiler.js]: Okay thanks. I wasn't sure about that.

File: lib/MultiCompiler.js [hunk 2]
```diff
@@ -109,50 +155,54 @@ module.exports = class MultiCompiler extends Tapable {
...
 
 		return new MultiWatching(watchings, this);
 	}
 
 	run(callback) {
 		const allStats = this.compilers.map(() => null);
-		this.runWithDependencies(this.compilers, ((compiler, callback) => {
-			const compilerIdx = this.compilers.indexOf(compiler);
-			compiler.run((err, stats) => {
+		if(this.validateDependencies(callback)) {
```
Comment (sokra) [inline lib/MultiCompiler.js]: I guess this validation could be omitted as `runWithDependencies` do the validation

File: test/MultiCompiler.test.js [hunk 3]
```diff
@@ -397,6 +397,59 @@ describe("MultiCompiler", () => {
...
+
+			it("should call the callback with an error message", () => {
+				env.compiler1WatchCallbacks.length.should.be.exactly(0);
+				env.compiler2WatchCallbacks.length.should.be.exactly(0);
+				env.callback.callCount.should.be.exactly(1);
+				env.callback.getCall(0).args[0].should.be.Error();
+				should(env.callback.getCall(0).args[1]).be.undefined();
+			});
+		});
+
```
Comment (sokra) [inline test/MultiCompiler.test.js]: Could you add a test with this configuration?

``` js
{
  name: "a",
},
{
  name: "b",
  dependencies: ["a", "c"]
},
{
  name: "c",
  dependencies: ["b"]
}
```

This is a test for `if(!edges.find(e => e.target === target))`

File: lib/MultiCompiler.js [hunk 4]
```diff
@@ -75,6 +75,52 @@ module.exports = class MultiCompiler extends Tapable {
...
+							source,
+							target
+						});
+					}
+				}
+			}
+		}
+		const errors = missing.map((m) => `Compiler dependency \`${m}\` not found.`);
+		const stack = this.compilers.filter((c) => !edges.find((e) => e.target === c));
+		const sorted = [];
```
Comment (sokra) [inline lib/MultiCompiler.js]: sorted and done could be removed.

File: lib/MultiCompiler.js [hunk 5]
```diff
@@ -75,6 +75,52 @@ module.exports = class MultiCompiler extends Tapable {
...
+				done.push(edge);
+				edges.splice(edges.indexOf(edge), 1);
+				const target = edge.target;
+				if(!edges.find(e => e.target === target)) {
+					stack.push(target);
+				}
+			}
+		}
+		if(edges.length > 0) {
+			errors.unshift("Circular dependency found in compiler dependencies.");
```
Comment (sokra) [inline lib/MultiCompiler.js]: Could you add a summary of all remaining edges?

```
Circular dependency found in compiler dependencies.
compiler1 -> compiler2
compiler2 -> compiler3
```

File: lib/MultiCompiler.js [hunk 6]
```diff
@@ -75,6 +75,52 @@ module.exports = class MultiCompiler extends Tapable {
 		});
 	}
 
+	validateDependencies(callback) {
+		const edges = [];
```
Comment (sokra) [inline lib/MultiCompiler.js]: Use a `Set` for edges to have an efficient `delete`

File: lib/MultiCompiler.js (hunk 2 above)
Comment (rrharvey) [reply lib/MultiCompiler.js]: I had it that way at first but compiler errors are [ignored](https://github.com/webpack/webpack/blob/622675993d72c6ea7d70cd2e503fd9416f940b2b/lib/MultiCompiler.js#L137) by the watcher. Since this is a configuration error that cannot be recovered should it report the error and exit?

**Comment by sokra** [comment]
Thanks
