### PR TITLE
hide loaders in HMR log message

### LINKED ISSUE #4452: NamedModulesPlugin returns file name prefixed with loaders string
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
webpack HMR + NamedModulesPlugin returns a huge string with loaders before the actual path of the updated file.

see console message 
```bash
[HMR] Updated modules:
log-apply-result.js?ad29:22 [HMR]  - ./node_modules/babel-loader/lib/index.js?presets[]=/web/blocklevel/blue-next/packages/blue-scripts/node_modules/babel-preset-es2015/lib/index.js&presets[]=/web/blocklevel/blue-next/packages/blue-scripts/node_modules/babel-preset-stage-2/lib/index.js&plugins[]=/web/blocklevel/blue-next/packages/blue-scripts/node_modules/babel-plugin-transform-regenerator/lib/index.js!./node_modules/eslint-loader/index.js?configFile=/web/blocklevel/blue-next/packages/eslint-config-blocklevel/index.js!./src/app/page/home/home.js
log-apply-result.js?ad29:22 [HMR]  - ./src/app/page/home/home.vue
dev-server.js?7993:27 [HMR] App is up to date.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
There's no need to steps. A normal webpack configuration will give the same result: the length it's just matter of how many loaders or how do you call them ( i.e. using `require.resolve` )

example of a `babel-loader` implementation 

```js
{
  test: /\.js$/,
  loader: 'babel-loader',
  exclude: /node_modules|build/,
  options: {
    presets: [
      require.resolve('babel-preset-es2015'),
      require.resolve('babel-preset-stage-2')
    ],
    plugins: [
      require.resolve('babel-plugin-transform-regenerator')
    ]
  }
}
```

**What is the expected behavior?**
I would like to be aware of which files are updated without the entire loader string attached to it, because makes the console too messy and the file it's unreadable 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: MacOS Sierra
node: v7.4.0
webpack: 2.2.1

### PR DESCRIPTION
**Pull request by rrharvey**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
No. I didn't see any tests for the HMR client.

**If relevant, link to documentation update:**

**Summary**
Remove loader information from the updated modules HMR log message. Fixes #4452

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

File: hot/log.js [hunk 1]
```diff
@@ -9,6 +11,12 @@ module.exports = function(level, msg) {
 		return console.error(msg);
 };
 
+module.exports.group = console.group || dummy;
```
Comment (sokra) [inline hot/log.js]: These function should respect the log level.

File: hot/log-apply-result.js [hunk 2]
```diff
@@ -20,7 +20,14 @@ module.exports = function(updatedModules, renewedModules) {
 	} else {
 		log("info", "[HMR] Updated modules:");
 		renewedModules.forEach(function(moduleId) {
-			log("info", "[HMR]  - " + moduleId);
+			if(typeof moduleId === "string") {
```
Comment (sokra) [inline hot/log-apply-result.js]: Also check if moduleId contains a `!` at all.

**Comment by sokra** [comment]
Thanks
