### PR TITLE
@ fix 8297 issues

### LINKED ISSUE #8297: HMR can't work when entry  is Numeric string and the mode value is development
# Bug report

**What is the current behavior?**
HMR can't work when entry is Numeric string 

**If the current behavior is a bug, please provide the steps to reproduce.**
1.  Has config.js like this
```javascript
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');


module.exports = {
    mode: 'development',
    context: path.resolve(__dirname, './'),
    entry: {
        '404': './404.js'
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: 'index.js',
        publicPath: '/'
    },
    devServer: {
        clientLogLevel: 'warning',
        hot: true,
        contentBase: [path.join(__dirname, 'public'), path.join(__dirname, 'assets')],
        compress: true,
        host: 'localhost',
        port: 8080,
        open:false,
        overlay: {warnings: false, errors: true},
        publicPath: '/',
        watchOptions: {
            poll: false,
        }
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname, './index.html'),
            filename: 'index' + '.html'
        })
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                loaders: ['babel-loader?cacheDirectory=true'],
                exclude: /node_modules/
            },
            {
                test: /\.(html)$/,
                loader: 'html-loader',
                options: {
                    attrs: ['data-src']
                }
            }
        ]
    }
};
```
2.  Excuting **"webpack-dev-server --inline --progress --color --profile --config webpack.config.js** in  terminal

3. Modify '404.js'  and look at browser changes,

4. Browser has not changed and if you open the console in browser, you will see such infomation like this, **[HMR] Update failed: ReferenceError: installedChunks is not defined**

**What is the expected behavior?**
Browser changed

**Other relevant information:**
webpack version:  4.23.1
Node.js version: 10.0.0
Operating System: MacOS mojave 10.14
Additional tools: None

### PR DESCRIPTION
**Pull request by JackyTianer**
#8297 when entry name is a number 
like 
> entry: { '404' :  '404.js'}

HMR can't correct work;

**What kind of change does this PR introduce?**
bugfix, fixed #8297 

**Did you add tests for your changes?**
Yes

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

File: lib/HotModuleReplacementPlugin.js [hunk 1]
```diff
@@ -253,7 +253,12 @@ module.exports = class HotModuleReplacementPlugin {
...
 						for (const key of Object.keys(records.chunkHashs)) {
-							const chunkId = isNaN(+key) ? key : +key;
+							let chunkId;
+							if (compiler.options.optimization.namedChunks) {
+								chunkId = key;
+							} else {
+								chunkId = isNaN(+key) ? key : +key;
+							}
 							const currentChunk = compilation.chunks.find(
 								chunk => chunk.id === chunkId
```
Comment (sokra) [inline lib/HotModuleReplacementPlugin.js]: ``chunk => `${chunk.id}` === key``

Stringify chunk of instead of numberifing key

File: lib/HotModuleReplacementPlugin.js [hunk 2]
```diff
@@ -253,7 +253,12 @@ module.exports = class HotModuleReplacementPlugin {
 							c: {}
 						};
 						for (const key of Object.keys(records.chunkHashs)) {
-							const chunkId = isNaN(+key) ? key : +key;
+							let chunkId;
+							if (compiler.options.optimization.namedChunks) {
```
Comment (sokra) [inline lib/HotModuleReplacementPlugin.js]: Avoid accessing Compiler options

File: lib/HotModuleReplacementPlugin.js (hunk 1 above)
Comment (JackyTianer) [reply lib/HotModuleReplacementPlugin.js]: Cool, get it. i'm trying add a test case at the PR

File: test/HotModuleReplacementPlugin.test.js [hunk 3]
```diff
@@ -97,4 +97,78 @@ describe("HotModuleReplacementPlugin", () => {
...
+					fs.writeFileSync(statsFile3, stats.toString());
+					const result = JSON.parse(
+						stats.compilation.assets[`${hash}.hot-update.json`].source()
+					)["c"][`${trunkName}`];
+					expect(result).toBe(true);
+					done();
+				});
+			});
+		});
+	});
```
Comment (sokra) [inline test/HotModuleReplacementPlugin.test.js]: This test case doesn't really run the code you changed, does it?

You can take a look at the `test/hotCases` folder where the tests for HMR are placed. You can `module.hot.accept()` the entry point.

File: package.json [hunk 4]
```diff
@@ -107,6 +107,7 @@
     "test": "node --max-old-space-size=4096 --trace-deprecation node_modules/jest-cli/bin/jest",
     "test:update-snapshots": "yarn jest -u",
     "test:integration": "node --max-old-space-size=4096 --trace-deprecation node_modules/jest-cli/bin/jest --testMatch \"<rootDir>/test/*.test.js\"",
+    "test:HMR": "node --max-old-space-size=4096 --trace-deprecation node_modules/jest-cli/bin/jest --testMatch \"<rootDir>/test/{HotModuleReplacementPlugin}.test.js\"",
```
Comment (sokra) [inline package.json]: Not needed. You can run `yarn jest HotModuleReplacementPlugin`. It also runs as part of the `yarn test:integration`.

Comment (JackyTianer) [reply package.json]: Thank for your help

File: test/HotModuleReplacementPlugin.test.js (hunk 3 above)
Comment (JackyTianer) [reply test/HotModuleReplacementPlugin.test.js]: @sokra Hi, thanks for your review, but i think, this case cover my changed, because when i run the case in the older code, i got an error.  i look at the `test/hotCases` folder, but i dont know  how can i run these cases

**Comment by sokra** [comment]
Thanks
