### PR TITLE
fix: compatibility `__non_webpack_require__` with ES modules

### LINKED ISSUE #17306: bug - __non_webpack_require__ is replaced on `require` in ESM
We see the same thing as @johnmanko's *case 2* ([code](https://github.com/serverless-dns/serverless-dns/tree/f2c0b9982b) / [webpack.config](https://github.com/serverless-dns/serverless-dns/blob/f2c0b9982b/webpack.fly.cjs) / [package.json](https://github.com/serverless-dns/serverless-dns/blob/f2c0b9982b/package.json)):

```sh
git clone git@github.com:serverless-dns/serverless-dns.git
git checkout -b fail f2c0b9982b
npm run build:fly
node ./dist/fly.mjs
```

_Originally posted by @ignoramous in https://github.com/webpack/webpack/issues/16029#issuecomment-1573594432_

### PR DESCRIPTION
**Pull request by alexander-akait**
fixes #17306

### <samp>🤖 Generated by Copilot at e3b1837</samp>

This pull request adds support for ES modules as output format for webpack. It updates the `APIPlugin` to handle different output formats, adds a new runtime global and a new initialization fragment for importing the `__WEBPACK_EXTERNAL_createRequire` function from the `module` built-in module in Node.js, and modifies the `ExternalModule` to handle the `node-commonjs` type. It also adds a new test case to verify the functionality and the API variable replacements.

### <samp>🤖 Generated by Copilot at e3b1837</samp>

*  Add support for ES modules as output format by modifying the expressions and runtime requirements for various webpack API variables ([link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-0b8525fd4794c93b31dd9e959e7e664fc6a79c68091046764063e3eace891764L27-R141), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-0b8525fd4794c93b31dd9e959e7e664fc6a79c68091046764063e3eace891764R147-R148), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-f01e290c9357ee8254e5ae51beb6a7225ced7fc41e32f3a0faf68bd8142738cbR66-R68), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-f01e290c9357ee8254e5ae51beb6a7225ced7fc41e32f3a0faf68bd8142738cbL110-R126), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-c3d58ece2e36cf9e319d260abb918fbfa8c8f0948c95d3f39b29907ea22ed30fR382-R386), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-01c0ec17c8c82af2e0c115384800d0d827f42365b28f0d37684cf7afc2b6d53aL371-R373), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-820a04017e95cec05fd58ca44cd7f6c9cfa5b698a144471d5a0f523932486c56R940-R951))
*  Add a test case for the feature by creating a `webpack.config.js` file that sets the output format to `module` and `iife`, defines some external modules, and adds a plugin that emits some assets ([link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-cf969008f89a6a5b67f0d790ab9783dee39b96481285188c730e742b52ea79a4R1-R58))
*  Add some test modules that use different import and export syntaxes, the `__non_webpack_require__` variable, and the `__WEBPACK_EXTERNAL_createRequire` function, and assert their values in `index.js` ([link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-65ad6c4a8052ea70922b17094eb0e50b640022dbc812d76fa037c051a759bbbbR1), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-169bb1109eb2ddd09eeec4820c326d066060f15f8e6210f2ab039b4aed70b493R1-R16), [link](https://github.com/webpack/webpack/pull/17308/files?diff=unified&w=0#diff-623817666b785426dc5112436b4134722c51463a42b72d41e7b9d2781ecf603fR1))

### CODE REVIEW

File: lib/node/ReadFileCompileAsyncWasmPlugin.js [hunk 1]
```diff
@@ -48,7 +49,7 @@ class ReadFileCompileAsyncWasmPlugin {
 							Template.asString([
 								"Promise.all([import('fs'), import('url')]).then(([{ readFile }, { URL }]) => new Promise((resolve, reject) => {",
 								Template.indent([
-									`readFile(new URL(${path}, import.meta.url), (err, buffer) => {`,
+									`readFile(new URL(${path}, ${importMetaName}.url), (err, buffer) => {`,
```
Comment (alexander-akait) [inline lib/node/ReadFileCompileAsyncWasmPlugin.js:52]: We don't respect it before, so we can consider it as a bugfix

File: lib/ExternalModule.js [hunk 2]
```diff
@@ -104,31 +107,28 @@ const getSourceForCommonJsExternal = moduleAndSpecifiers => {
...
+const getSourceForCommonJsExternalInNodeModule = (
+	moduleAndSpecifiers,
+	compilation
+) => {
+	const { importMetaName } = compilation.outputOptions;
 	if (!Array.isArray(moduleAndSpecifiers)) {
 		return {
-			expression: `__WEBPACK_EXTERNAL_createRequire(import.meta.url)(${JSON.stringify(
+			runtimeRequirements: RUNTIME_REQUIREMENTS_FOR_CREATE_REQUIRE,
+			expression: `__WEBPACK_EXTERNAL_createRequire(${importMetaName}.url)(${JSON.stringify(
```
Comment (alexander-akait) [inline lib/ExternalModule.js:121]: We don't respect `importMetaName` before, so we can consider it as a bugfix too

File: test/configCases/output-module/issue-16040/index.js [hunk 3]
```diff
@@ -1,8 +1,6 @@
 import foo from "./foo.js";
 import bar from "./bar.js";
 
-console.log(foo + bar);
```
Comment (alexander-akait) [inline test/configCases/output-module/issue-16040/index.js:4]: Not a good due to only `console.log`, I think in future we need refactor tests (step by step) to avoid using `console.log` to check that code is works without any problems

File: test/configCases/web/prefetch-preload-module/webpack.config.js [hunk 4]
```diff
@@ -9,7 +9,7 @@ module.exports = {
 	output: {
 		publicPath: "",
 		module: true,
-		filename: "bundle0.js",
+		filename: "bundle0.mjs",
```
Comment (alexander-akait) [inline test/configCases/web/prefetch-preload-module/webpack.config.js:12]: Refactor test to be real ESM and test using ESM env
