### PR TITLE
fix imports order

### LINKED ISSUE #11871: Order of imported (or exported) values is not respected between dev and prod env
# Bug report

**What is the current behavior?**

Order of imported values (when using `import * as values`) is not respected between dev and prod environment

**If the current behavior is a bug, please provide the steps to reproduce.**

foo.js:

```
export const W = 'w';
export const A = 'a';
```

bar.js:

```
import * as values from './foo.js':

console.log(Object.keys(values));
```

webpack 4 dev + prod will output ['W', 'A'];
webpack 5 dev will output ['W', 'A'];
webpack 5 prod will output ['A', 'W']

**What is the expected behavior?**

It should, at least, be the same between dev and production environment for webpack 5, and would be best to keep the same ordrer as declared (like webpack 4 or dev in webpack 5)

**Other relevant information:**

webpack version: 5.3.1
Node.js version: 14.13.1
Operating System: linux
Additional tools: webpack-dev-server

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**
fixes #11871 

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/dependencies/HarmonyExportInitFragment.js [hunk 1]
```diff
@@ -145,11 +145,12 @@ class HarmonyExportInitFragment extends InitFragment {
 				? `/* unused harmony export ${first(this.unusedExports)} */\n`
 				: "";
 		const definitions = [];
-		for (const [key, value] of this.exportMap) {
+		const orderedExportMap = Array.from(this.exportMap.keys()).sort();
+		for (const key of orderedExportMap) {
```
Comment (sokra) [inline lib/dependencies/HarmonyExportInitFragment.js:149]:
```suggestion
		const orderedExportMap = Array.from(this.exportMap).sort(([a], [b]) => a < b ? -1 : 1);
		for (const [key, value] of orderedExportMap) {
```

That should be a little bit more performant as it isn't calling `get()` many times.

**Review by sokra — CHANGES_REQUESTED** [review]

**Comment by sokra** [comment]
Thanks
