### PR TITLE
Use Promise only when chunk load is triggered

### LINKED ISSUE #4916: webpack 2.6.0 can't find variable: Promise on require async
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

Having ReferenceError: Can't find variable: Promise when using `require(['dep'], callback)`

**If the current behavior is a bug, please provide the steps to reproduce.**

So, I'm using karma to run tests on phantomjs with webpack, and phantomjs doesn't have native promises. So, this is why I have this in my webpack.config (also, for older browsers):

```javascript
...
new webpack.ProvidePlugin({
  Promise: 'es6-promise-promise'
}),
...
```

Then, on my code, I could do something like this, and everything worked fine until `webpack@2.5.1` (and under, in fact, since 1.x this worked fine):

```javascript
console.log('promise', Promise);
require(['left-pad'], function (leftpad) {
  // ...
});
```

But then, simply by upgrading to `webpack@2.6.0`, I get the `ReferenceError: Can't find variable: Promise` error now.

I believe this is because webpack uses promises to load the chunks, and somehow stopped replacing variables from ProvidePlugin on its own boilerplate.

**What is the expected behavior?**

Promises should work when defined on ProvidePlugin, even if it is webpack generated code, right?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

macOS, but also happened on ubuntu. Node 6.9. Webpack 2.6.0

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
no

**If relevant, link to documentation update:**
n/a

**Summary**
Use Promise only when chunk load is triggered
don't use it in initialisation
fixes #4916

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

File: lib/JsonpMainTemplatePlugin.js [hunk 1]
```diff
@@ -81,26 +79,27 @@ class JsonpMainTemplatePlugin {
 		});
 		mainTemplate.plugin("require-ensure", function(_, chunk, hash) {
 			return this.asString([
-				"if(installedChunks[chunkId] === 0) {",
+				"var installedChunkData = installedChunks[chunkId];",
+				"if(installedChunkData === 0) {",
 				this.indent([
-					"return resolvedPromise;"
+					"return new Promise(function(resolve) { resolve(); });"
```
Comment (timse) [inline lib/JsonpMainTemplatePlugin.js]: can't this just be `Promise.resolve()` ?
