### PR TITLE
Fix consumes function

### LINKED ISSUE #16626: Infinity loop in moduleFederationPlugin, in runtime loading module
# Bug report

**What is the current behavior?**
If your shared module do not import all modules in main index.js file(use for tree shaking), fallback module infitity looping browser runtime.
[Consumes](https://github.com/webpack/webpack/blob/main/lib/sharing/ConsumeSharedRuntimeModule.js#L311) function should call infinity, while maximum call stack size exceeded.

**If the current behavior is a bug, please provide the steps to reproduce.**
#### Provider:
```
{
  ...,
  "ui/blocks/address/address": {
    "import": "./libs/ui/blocks/address/address.js",
    "requiredVersion": "^164.1.0",
    "version": "164.1.0",
    "packageName": "ui/build/blocks/address/address.js"
  },
  "ui/blocks/address/geoObjectHelper": {
    "import": "./libs/ui/blocks/address/geoObjectHelper.js",
    "requiredVersion": "^164.1.0",
    "version": "164.1.0",
    "packageName": "ui/build/blocks/address/geoObjectHelper.js"
  },
  "ui/blocks/address/location": {
    "import": "./libs/ui/blocks/address/location.js",
    "requiredVersion": "^164.1.0",
    "version": "164.1.0",
    "packageName": "ui/build/blocks/address/location.js"
  },
  ...
}
```
#### Consumer:
```
...,
{
  "ui/blocks/address/address": {
    "requiredVersion": "^168.1.3",
    "version": "168.1.3",
  },
  "ui/blocks/address/geoObjectHelper": {
    "requiredVersion": "^168.1.3",
    "version": "168.1.3",
  },
  "ui/blocks/address/location": {
    "requiredVersion": "^168.1.3",
    "version": "168.1.3",
  }
},
...
```
#### Example moduleToHandlerMapping
```
...,
"webpack/sharing/consume/default/ui/blocks/address/addressContent/ui/blocks/address/address": () => (loadStrictVersionCheckFallback("default", "ui/blocks/address/address", [1,168,1,3], () => (__webpack_require__.e("ui-fallback").then(() => (() => (__webpack_require__(/*! ui/blocks/address/addressContent */ "./node_modules/@hh.ru/ui/build/blocks/address/addressContent.js"))))))),
"webpack/sharing/consume/default/ui/blocks/address/addressHeader/ui/blocks/address/geoObjectHelper": () => (loadStrictVersionCheckFallback("default", "ui/blocks/address/geoObjectHelper", [1,168,1,3], () => (__webpack_require__.e("ui-fallback").then(() => (() => (__webpack_require__(/*! ui/blocks/address/addressHeader */ "./node_modules/@hh.ru/ui/build/blocks/address/addressHeader.js"))))))),
"webpack/sharing/consume/default/ui/blocks/address/addressFooter/ui/blocks/address/location": () => (loadStrictVersionCheckFallback("default", "ui/blocks/address/location", [1,168,1,3], () => (__webpack_require__.e("ui-fallback").then(() => (() => (__webpack_require__(/*! ui/blocks/address/addressFooter */ "./node_modules/@hh.ru/ui/build/blocks/address/addressFooter.js"))))))),
...
```

#### Example ChunkMapping
```
{
    'ui-fallback': [
        'webpack/sharing/consume/default/ui/blocks/address/address',
        'webpack/sharing/consume/default/react/react',
        'webpack/sharing/consume/default/ui/blocks/address/geoObjectHelper/ui/blocks/address/geoObjectHelper',
        'webpack/sharing/consume/default/ui/blocks/address/location/ui/blocks/address/location',
    ],
    ...
}
```

#### Register
```
...,
register("ui/blocks/address/address", "168.1.3", () => (Promise.all([__webpack_require__.e("ui-fallback"), __webpack_require__.e("vendors-node_modules_react_jsx-runtime_js")]).then(() => (() => (__webpack_require__(/*! ./node_modules/ui/blocks/address/address.js */ "./node_modules/ui/blocks/address/address.js"))))));
...,
```
#### Example 
Consumer front should use fallback version, but runtime code is falled by maximum call stack.
I debugged the problem and found the problematic place: https://github.com/webpack/webpack/pull/16625
return statement not work in forEach loop. I replaced to for loop and add check to start init modules(it fixes infinity looping).

**What is the expected behavior?**
Fallback modules loaded without infinity looping

**Other relevant information:**
webpack version: 5.62.0
Node.js version: ^14 | ^16 | ^18
Operating System: macos 13.1
Additional tools: chrome browser

### PR DESCRIPTION
**Pull request by AndreyGladkov**
**What kind of change does this PR introduce?**
It is bugfix.
If your shared module do not import all modules in main index.js file(use for tree shaking), fallback module infitity looping browser runtime.
I add check if module start inited, it fixed infinity looping.

fixes #16626
 

**Did you add tests for your changes?**
No

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
No needs to change the documentation

### CODE REVIEW

**Comment by alexander-akait** [comment]
Looks like tests are failed, also can you accept CLA?

**Comment by AndreyGladkov** [comment]
> Looks like tests are failed, also can you accept CLA?

I accept CLA and 20 successful checks. How to run 18 expected checks?

**Comment by AndreyGladkov** [comment]
@alexander-akait take a look, please

**Comment by ScriptedAlchemy** [comment]
@alexander-akait bump

**Review by alexander-akait — APPROVED** [review]

File: lib/sharing/ConsumeSharedRuntimeModule.js [hunk 1]
```diff
@@ -315,6 +316,7 @@ class ConsumeSharedRuntimeModule extends RuntimeModule {
 									"id",
 									[
 										`if(${RuntimeGlobals.hasOwnProperty}(installedModules, id)) return promises.push(installedModules[id]);`,
```
Comment (sokra) [inline lib/sharing/ConsumeSharedRuntimeModule.js:318]: Shouldn't the `installedModules` object already do the same?

Comment (AndreyGladkov) [reply lib/sharing/ConsumeSharedRuntimeModule.js:318]: No, installedModules this is the map of installed modules. startedInstallModules this is the map of started install modules, not loaded and not installed, otherwise "promise looping" in browser runtime.

Comment (AndreyGladkov) [reply lib/sharing/ConsumeSharedRuntimeModule.js:318]: An alternative way to fix it is to remove modules from cache groups. Need add to test function filter by "consume" and "provide" modules.
It seems to me that this is the correct way to fix, if possible remove these modules from user cache groups rules.

**Comment by Saafine** [comment]
This helped to fix infinite loop breaking my application. Thank you

**Comment by alexander-akait** [comment]
Can anyone problem a minimum reproducible test repo?

**Comment by AndreyGladkov** [comment]
>Can anyone problem a minimum reproducible test repo?

hi here is an example:

https://github.com/AndreyGladkov/webpack-mfp-infitity-loop-example/tree/main/dynamic-system-host#bug-description

**Comment by stevezhaoUS** [comment]
No updates on this one?
Just few weeks ago, we discovered that the MFE website breaks on safari & Firefox, the I created a patch from this fix, it fix the infinite loop issue on those browsers. So I'm wondering when this fix can be merge? or there is another workaround?

**Comment by ScriptedAlchemy** [comment]
I'm forking module federation so I'll address this during the rebuild. Will try and pr back to webpack but either way should be able to support this soon

**Review by alexander-akait — APPROVED** [review]
