### PR TITLE
handle several resources in ContextModule

### LINKED ISSUE #11335: context module doesn't work with array of aliases
**webpack.config.js**

```js
module.exports = {
    mode: 'development',
    devtool: 'source-map',
    entry: './src/main/index.js',
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
    },
    resolve: {
        alias: {
            app: [path.join(__dirname, 'src/main'), path.join(__dirname, 'src/foo')]
        }
    }
};
```

**index.js**

```
import a from 'app/widgets/a';
import b from 'app/widgets/b';
import c from 'app/widgets/c';

console.log('\nstatic import\n');

a();
b();
c();

console.log('\ndynamic import\n');

const load = id => import(/* webpackMode: "eager" */ `app/widgets/${id}`);

load('a').then(ad => ad.default())

    .then(() => load('b'))
    .then(bd => bd.default())

    .then(() => load('c'))
    .then(cd => cd.default())

    .catch(err => console.log(err));
```

Reproducible test repo - https://github.com/homobel/webpack5-dynamic-import

Ref: https://github.com/webpack/webpack/issues/9802#issuecomment-674073005

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

bugfix
fixes #11335 

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

File: lib/ContextModule.js [hunk 1]
```diff
@@ -220,7 +235,16 @@ class ContextModule extends Module {
...
-		let identifier = requestShortener.shorten(this.context) + "/";
+		let identifier;
+		if (this.context) {
+			identifier = requestShortener.shorten(this.context) + "/";
+		} else if (typeof this.options.resource === "string") {
+			identifier = requestShortener.shorten(this.options.resource) + "/";
+		} else {
+			identifier =
+				this.options.resource.map(r => requestShortener.shorten(r)).join("/") +
+				"/";
```
Comment (sokra) [inline lib/ContextModule.js:246]:
```suggestion
				this.options.resource.map(r => requestShortener.shorten(r) + "/").join(" ");
```

File: lib/ContextModule.js [hunk 2]
```diff
@@ -270,11 +294,30 @@ class ContextModule extends Module {
...
+				options.associatedObjectForCache
+			);
+		} else {
+			const arr = [];
+			for (const res of this.options.resource) {
+				arr.push(
+					contextify(options.context, res, options.associatedObjectForCache)
+				);
+			}
+			identifier = arr.join("|");
```
Comment (sokra) [inline lib/ContextModule.js:318]:
```suggestion
			identifier = arr.join(" ");
```

**Review by sokra — CHANGES_REQUESTED** [review]
nitpicks, otherwise fine

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
