### PR TITLE
fix ProgressPlugin log

### LINKED ISSUE #14805: fix output of ProgressPlugin
> Please then keep the conversation consistent, the problem described above has nothing to do with `ProgressPlugin`. Even if it has anything to do with it, this is a transitive effect of the problem, so let's find out what you want to get and what happens now. What is the problem?

@alexander-akait ProgressPlugin starts printing output before we call `run` or `watch` this caused confusion into thinking compilation has started early. 

we also have suspicions that "occasionally" it does indeed start and continue without calling `.run/watch` but no proof on that yet, we will try to rule it out.

_Originally posted by @serkanyersen in https://github.com/webpack/webpack/issues/12481#issuecomment-767095046_

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**
fixes #14805 

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/ProgressPlugin.js [hunk 1]
```diff
@@ -537,9 +542,8 @@ class ProgressPlugin {
 				handler(0, "");
 			}
 		});
```
Comment (sokra) [inline lib/ProgressPlugin.js:544]: You probably want to change that `compiler.hooks.initialize` to `compiler.hooks.beforeRun`, instead of filtering 0% in the default logger with `wasLogged`

**Review by sokra — CHANGES_REQUESTED** [review]

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
