### PR TITLE
disallow global renaming in NodeStuffPlugin

### LINKED ISSUE #15401: Ambiguous behavior of node.global: true when webpack.DefinePlugin is used
# Bug report

**What is the current behavior?**
A global reference is not replaced when you set node.global: true and define a global object attribute with DefinePlugin
new webpack.DefinePlugin({'global.test': JSON.stringify('test')}). If you remove the DefinePlugin it works as expected

**If the current behavior is a bug, please provide the steps to reproduce.**
```
git clone https://github.com/astroza/webpack-global-concern
cd webpack-global-concern
yarn install
yarn build
cat out.js
```

```
var __webpack_exports__ = {};
var plsReplaceMyRightValue = global;
console.log(__webpack_require__.g, "test");
```

A global reference is still there. This is only an opinion but I think it is not consistent. Also, many people can lose a day figuring out why a global is still there. The output code does not run in a service worker environment because global does not exist.

**What is the expected behavior?**
```
var __webpack_exports__ = {};
var plsReplaceMyRightValue = __webpack_require__.g;
console.log(plsReplaceMyRightValue, "test");
```

**Other relevant information:**
webpack version:  5.69.0
Node.js version: v16.13.1
Operating System: MacOS 12.2.1
Additional tools: webpack-cli 4.9.2

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

fixes #15401 

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/NodeStuffPlugin.js [hunk 1]
```diff
@@ -69,6 +69,13 @@ class NodeStuffPlugin {
 									);
 								}
 							});
+						parser.hooks.canRename.for("global").tap(
```
Comment (vankop) [inline lib/NodeStuffPlugin.js:72]: there is no need to prevent renaming for `__dirname`/`__filename` since they should be always strings

**Review by sokra — CHANGES_REQUESTED** [review]
I think disabling renaming would break a scenario like:

``` js
var shouldBeGlobal = global;
expect(shouldBeGlobal.test).toBe("test");
```

---

Instead of disabling renaming, it would be better to handle renaming.

You can do that with the `rename` hook. On renaming I would expect the right side to be replaced with `__webpack_require__.g`.

I think that should do it:

					parser.hooks.rename.for("global").tap("NodeStuffPlugin", expr => {
						const dep = new ConstDependency(
							RuntimeGlobals.global,
							expr.range,
							[RuntimeGlobals.global]
						);
						dep.loc = expr.loc;
						parser.state.module.addPresentationalDependency(dep);
						return false;
					});

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
