### PR TITLE
fixes unused export bug

### LINKED ISSUE #11990: Webpack 5 incorrectly marking a reexport as unused
# Bug report

**What is the current behavior?**
When upgrading our app (a large Microsoft Office web application) from webpack 4 to webpack 5 we are getting an error like this:

boot.js:3914 Uncaught TypeError: (0 , lib.createTheme) is not a function
    at Object.844 (boot.js:3914)
    at __webpack_require__ (boot.js:3966)
    at boot.js:4207
    at boot.js:4208 

This issue only happens in production mode. More specifically, it happens when concatenateModules and unusedExports are set to true. 

To debug, I turned off minification and export mangling (the issue still repros) and I found that the 'createTheme' module is incorrectly being marked as 'unused'. One interesting thing to note about createTheme is that it is being imported from the `office-ui-fabric-react` npm package, which internally reexports that module from the `@uifabric/

Here is the chain of the re-exports from office-ui-fabric-react (which is in the middle of a rename to fluent-ui)
https://github.com/microsoft/fluentui/blob/master/packages/react/src/Theme.ts
https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/Theme.ts
https://github.com/microsoft/fluentui/blob/master/packages/theme/src/index.ts#L8

Here is the interesting code from the bundle, with comments saying it is an unused re-export
```javascript
  "createTheme": () => /* reexport */ /* unused export */ undefined,
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I was able to strip down our app into a minimal repro of the issue, it is in this github repo: https://github.com/christiango/webpack5-unused-export-bug

The readme there contains some notes from the investigation. One of the most interesting bits is that if we change any of these things, the issue no longer reproduces:

1. Making it only a single entry point (remove the logout entrypoint)
2. Switch the webpack mode to development
3. Set optimization.concatenateModules to false in the webpack config
4. Set optimization.usedExports to false in the webpack config
5. Switch the dynamic import in ErrorDialog.js to a static import

**What is the expected behavior?**
The "createTheme" function in the repro should not crash

**Other relevant information:**
webpack version:  5.4.0
Node.js version:  12.14.0
Operating System: Windows 10
Additional tools:

### PR DESCRIPTION
**Pull request by sokra**
fixes #11990

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/ExportsInfo.js [hunk 1]
```diff
@@ -1290,6 +1293,24 @@ class ExportInfo {
...
+	 * @param {ModuleGraph} moduleGraph the module graph
+	 * @param {function({ module: Module, export: string[] | undefined }): boolean} resolveTargetFilter filter function to further resolve target
+	 * @returns {{ module: Module, export: string[] | undefined } | undefined} the target
+	 */
+	moveTarget(moduleGraph, resolveTargetFilter) {
+		const target = this._getTarget(moduleGraph, resolveTargetFilter, undefined);
+		if (target === CIRCULAR) return undefined;
+		if (!target) return undefined;
+		this._target.clear();
+		this._target.set(undefined, {
```
Comment (IWANABETHATGUY) [inline lib/ExportsInfo.js:1307]: Hello tobias, Would you mind explaining why set undefined here?
