### PR TITLE
fix: create contexts in object shorthand syntax

### LINKED ISSUE #14545: when unknownContext 'require' encounters object shorthand syntax, it generates invalid code
# Bug report

**What is the current behavior?**

I imported the `vm2` package in my project, and then i found the code generated was invalid.

I found this line caused this problem

https://github.com/patriksimek/vm2/blob/3.9.4/lib/main.js#L1338

`require` function was used in object shorthand syntax

**If the current behavior is a bug, please provide the steps to reproduce.**

pack flowing code:
```javascript
const obj = { require }
```
got:

```javascript
const obj = {  __webpack_require__(1) }
```

**What is the expected behavior?**

it should generate:
```javascript
const obj = { require:  __webpack_require__(1) }
```
**Other relevant information:**
webpack version:  5.59.0
Node.js version: v16.10.0
Operating System: Ubuntu20.04.3
Additional tools:

### PR DESCRIPTION
**Pull request by peterq**
**What kind of change does this PR introduce?**

close #14545

**Did you add tests for your changes?**

Yes.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

No need.

### CODE REVIEW

File: lib/dependencies/CommonJsRequireContextDependency.js [hunk 1]
```diff
@@ -10,11 +10,12 @@ const ContextDependency = require("./ContextDependency");
 const ContextDependencyTemplateAsRequireCall = require("./ContextDependencyTemplateAsRequireCall");
 
 class CommonJsRequireContextDependency extends ContextDependency {
-	constructor(options, range, valueRange) {
+	constructor(options, range, valueRange, inShorthand) {
 		super(options);
 
 		this.range = range;
 		this.valueRange = valueRange;
+		this.inShorthand = inShorthand;
```
Comment (sokra) [inline lib/dependencies/CommonJsRequireContextDependency.js:18]:
```suggestion
		// inShorthand must be serialized by subclasses that use it
		this.inShorthand = inShorthand;
```

**Review by sokra — CHANGES_REQUESTED** [review]

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
