### PR TITLE
fix: unsupported function defined inside a condition block. #7263

### LINKED ISSUE #7263: `onScriptComplete` is not defined under Firefox 40
# Bug report

**What is the current behavior?**

During bootstrap, `onScriptComplete` has an error script when runing under Firefox 40+

**If the current behavior is a bug, please provide the POC.**

Error script was thrown by the script generated by `lib/web/JsonpMainTemplatePlugin.js`.

I have tested that it did not seem the problem of hoisted, as the following snippet has worked under Firefox 40:

```js
(function () {
    console.log(test);
    function test() {}
})();
```

The real reason is that function `onScriptComplete` has been declared inside a condition block rather than a function block (As a common sense, functions declaration must be placed at the root of a function block, **no-inner-declaration**):

```js
if (true) {
    /** throw an error: func is not defined */
    console.log(func);
    function func () {}
}
```

**Other relevant information:**
webpack version:  4.4.1
Node.js version: v7.10.1
Operating System: Windows 10

### PR DESCRIPTION
**Pull request by aleen42**
**Issue Reference**

fixes #7263 

**What kind of change does this PR introduce?**

Call the method `onScriptComplete` after its declaration as there should ben an error of references under Friefox 40, when it has been declared inside a conditon block, rather than the top block inside a function.

**Did you add tests for your changes?**

No needs.

**Does this PR introduce a breaking change?**

Solve the problem under Firefox 40.

**What needs to be documented once your changes are merged?**

No needs.

### CODE REVIEW

**Comment by aleen42** [comment]
A separate PR for fixing remaining problems of #7210.

**Comment by ooflorent** [comment]
`function` declarations are hoisted. This should not be an issue.

**Comment by aleen42** [comment]
@ooflorent hoisted does not work inside condition block under FireFox.

**Comment by aleen42** [comment]
@ooflorent It seems like my fault, and the result should not be an issue:

image

**Comment by sokra** [comment]
So we can close it?

**Comment by aleen42** [comment]
It depends on you all. In my opinion, it is still not proper to declare function inside a condition block, a.k.a inner-declaration, according to a document of ESLint, and I will submit another commit for this.

**Comment by aleen42** [comment]
Hoisted variables should be avoided, like using `let` or `const` within ES6, rather than `var`.

**Comment by aleen42** [comment]
@sokra It seems that the "stats test cases" has not already been matched?

File: lib/web/JsonpMainTemplatePlugin.js [hunk 1]
```diff
@@ -168,12 +169,7 @@ class JsonpMainTemplatePlugin {
 					),
 					"}",
 					"script.src = jsonpScriptSrc(chunkId);",
-					"var timeout = setTimeout(function(){",
-					Template.indent([
-						"onScriptComplete({ type: 'timeout', target: script });"
-					]),
-					`}, ${chunkLoadTimeout});`,
-					"function onScriptComplete(event) {",
+					"onScriptComplete = function (event) {",
```
Comment (ooflorent) [inline lib/web/JsonpMainTemplatePlugin.js]: `function onScriptComplete(event) {` was fine

Comment (aleen42) [reply lib/web/JsonpMainTemplatePlugin.js]: As an inner declaration, it was not fine to some extends.

Comment (aleen42) [reply lib/web/JsonpMainTemplatePlugin.js]: https://eslint.org/docs/rules/no-inner-declarations

**Comment by sokra** [comment]
@aleen42 please also sign the CLA

**Comment by aleen42** [comment]
I have signed it and can u check this? @sokra

**Comment by sokra** [comment]
Thanks
