### PR TITLE
fix: Clear optimization bailouts on module.disconnect

### LINKED ISSUE #5562: ModuleConcatenation Bailout errors snowball on dev-server
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

On repeated incremental builds, the bundle size gets larger and larger per build:

```
  app.js   7.16 MB
login.js   1.48 MB

---

  app.js   7.36 MB
login.js   1.51 MB

---

  app.js   7.55 MB
login.js   1.55 MB

---

  app.js   7.65 MB
login.js   1.57 MB
```

After downloading one of these bloated bundles, I see:

```js
/* 853 */
/*!*******************************************************************!*\
  !*** ./ui/views/widgets/dialogs/DialogContainer.jsx + 14 modules ***!
  \*******************************************************************/
/*! exports provided: default */
/*! exports used: default */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/classCallCheck.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/extends.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/inherits.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/objectWithoutProperties.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/possibleConstructorReturn.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./ui/views/RootComponent.jsx because of ./ui/entry_webpack/browser.js */
/*! ModuleConcatenation bailout: Cannot concat with ./ui/views/mixins/Connect.jsx because of ./ui/views/AppMain.jsx */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/react/react.js (<- Module is not an ECMAScript module) */
.... lots, LOTS more of these...
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/classCallCheck.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/extends.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/inherits.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/objectWithoutProperties.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/babel-runtime/helpers/possibleConstructorReturn.js (<- Module is not an ECMAScript module) */
/*! ModuleConcatenation bailout: Cannot concat with ./ui/views/RootComponent.jsx because of ./ui/entry_webpack/browser.js */
/*! ModuleConcatenation bailout: Cannot concat with ./ui/views/mixins/Connect.jsx because of ./ui/views/AppMain.jsx */
/*! ModuleConcatenation bailout: Cannot concat with ./node_modules/react/react.js (<- Module is not an ECMAScript module) */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
eval("...
```

Expected behavior:

Webpack should not keep concatenating these error comments to the bundle.

After 100+ reloads, we see Node blow up "CALL_AND_RETRY_LAST", aka ENOMEM, and webpack-dev-server needs to be restarted.

### PR DESCRIPTION
**Pull request by STRML**
Ref: #5562

Fixes #5562.

**Did you add tests for your changes?**

No - will amend later with tests, first time w/Webpack tests and it's a bit overwhelming at the moment to get a hang of them.

**Summary**

See #5562: ModuleConcatenationPlugin errors snowball over time in incremental builds because this array is not cleared. After a while, the process will crash with an out of memory error.

**Does this PR introduce a breaking change?**

No.

### CODE REVIEW

File: lib/Module.js [hunk 1]
```diff
@@ -58,6 +58,7 @@ class Module extends DependenciesBlock {
 		this.providedExports = null;
 		this._chunks.clear();
 		this._chunksDebugIdent = undefined;
+		this.optimizationBailout = [];
```
Comment (sokra) [inline lib/Module.js]: Could you clear it by setting `length = 0`? This should avoid allocating many new objects.

Comment (STRML) [reply lib/Module.js]: Done

**Comment by sokra** [comment]
Thanks
