### PR TITLE
fix: use relative path in source map for context module

### LINKED ISSUE #15274: webpack sourcemap include absolute path
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

 https://github.com/xiaoxiangmoe/webpack-source-absolute-path-bug
* `git clone https://github.com/xiaoxiangmoe/webpack-source-absolute-path-bug.git`
* `cd webpack-source-absolute-path-bug`
* `yarn install && yarn build`

see file `src/index.js`

```js
const foo = Math.random() > 0.5 ? "a" : "b";
const m = require(`./foo/${foo}.js`);
console.log(m);
```

see file `dist/main.js.map.json` line 8

```json
{
  "version": 3,
  "file": "main.js",
  "mappings": "...",
  "sources": [
    "webpack:///./src/foo/a.js",
    "webpack:///./src/foo/b.js",
    "webpack:////Users/zhaojinxiang/repos/webpack-sourcemap-bug/src/foo|sync|/^\\.\\/.*\\.js$/",
    "webpack:///webpack/bootstrap",
    "webpack:///webpack/runtime/hasOwnProperty shorthand",
    "webpack:///./src/index.js"
  ],
}
```

You can find a absolute file path in line 8

**What is the expected behavior?**

It should be

```json
{
  "version": 3,
  "file": "main.js",
  "mappings": "...",
  "sources": [
    "webpack:///./src/foo/a.js",
    "webpack:///./src/foo/b.js",
    "webpack:///./src/foo|sync|/^\\.\\/.*\\.js$/",
    "webpack:///webpack/bootstrap",
    "webpack:///webpack/runtime/hasOwnProperty shorthand",
    "webpack:///./src/index.js"
  ],
}
```

**Other relevant information:**
webpack version:  5.67.0
Node.js version: v16.12.0
Operating System: macos 12.1

### PR DESCRIPTION
**Pull request by cool-little-fish**
**What kind of change does this PR introduce?**
bug fix #15274 

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

**Comment by cool-little-fish** [comment]
It seems there is cache problem, let me fix it..

File: lib/ContextModule.js [hunk 1]
```diff
@@ -1059,7 +1067,14 @@ module.exports = webpackEmptyAsyncContext;`;
...
 	getSource(sourceString) {
 		if (this.useSourceMap || this.useSimpleSourceMap) {
-			return new OriginalSource(sourceString, this.identifier());
+			return new OriginalSource(
+				sourceString,
+				makePathsRelative(
+					this.sourceOptions.context,
+					this.identifier(),
+					this.sourceOptions.cacheObj
+				)
```
Comment (sokra) [inline lib/ContextModule.js:1076]:
```suggestion
				`webpack://${makePathsRelative(
					this.context,
					this.identifier(),
					compilation && compilation.compiler.root
				)}`
```

File: lib/ContextModule.js [hunk 2]
```diff
@@ -394,6 +398,10 @@ class ContextModule extends Module {
 		this.buildInfo = {
 			snapshot: undefined
 		};
+		this.sourceOptions = {
+			context: options.context,
+			cacheObj: compilation.compiler.root
+		};
```
Comment (sokra) [inline lib/ContextModule.js:404]:
```suggestion
```

This would need to be serialized to be able to pass it from `build` to `codeGeneration`, but the `compilation.compiler.root` object is not serializable, so that's not possible here.

File: lib/ContextModule.js [hunk 3]
```diff
@@ -1059,7 +1067,14 @@ module.exports = webpackEmptyAsyncContext;`;
 
 	getSource(sourceString) {
```
Comment (sokra) [inline lib/ContextModule.js:1068]:
```suggestion
	getSource(sourceString, compilation) {
```

and call `getSource` with `compilation`.

But you will notice that you don't have a `compilation` in `codeGeneration`, so add that to the `CodeGenerationContext` as **optional** property (optional to not make it a breaking change).

In `Compilation.codeGeneration()` pass the `compilation` property to the context.

`associatedObjectForCache` is optional, so it's fine to omit it when `compilation` is not provided.

Add a TODO comment to `CodeGenerationContext` to make `compilation` required in webpack 6

File: lib/ContextModule.js (hunk 1 above)
Comment (sokra) [reply lib/ContextModule.js:1076]: @vankop when relanding the other ContextModule PR we need to handle an unset `this.context` here, e. g. via `this.context || compilation.compiler.context`

**Review by sokra — CHANGES_REQUESTED** [review]

File: lib/ContextModule.js (hunk 1 above)
Comment (cool-little-fish) [reply lib/ContextModule.js:1076]: em...one question,why here use context module's own context to get relative path instead of using the context from options

Comment (cool-little-fish) [reply lib/ContextModule.js:1076]: eg. if it will better to use compilation && compilation.option.context  ||  this.context

Comment (vankop) [reply lib/ContextModule.js]: module context is where nested context modules resolves. e.g.
you have files
```
/a/b/c
/a/b/b
```
then request
```js
import(`/a/b/${some}`)
```
will result in context `/a/b` (if no other resolving happen) since all submodules will be resolved related to this context => `./c`, `./b` (`/a/b/c` and `/a/b/b` respectively)

Comment (cool-little-fish) [reply lib/ContextModule.js]: that's right, but the case is different here, because there is module source name mapping, all module generated by webpack which name starts with `webpack://` will get its absolute path to find its module object. see,
https://github.com/webpack/webpack/blob/dfdc8b133d3d49371251e29efeefb9d31b982c9e/lib/SourceMapDevToolPlugin.js#L98

Comment (vankop) [reply lib/ContextModule.js]: ok, we can use only compiler context since `this.identifier()` has `context` part already..

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
