### PR TITLE
Fix: Add path separator to avoid file and folder name mixup(fixes #5576)

### LINKED ISSUE #5576: Inconsistent Path Resolving For Entry Module
## :bug: Inconsistent Path Resolving For Entry Module

**Webpack version:** 2.7.0
**Language:** all
**OS:** Ubuntu 16.04, macOS 10.12.6
**Type:** Bug Report
#### When It Works:
- `example.js` and `example/` exist
- `webpack example bundle.js`
- :arrow_right: WebPack compiles
#### When It Doesn't Work Because Of Inconsistencies
- `example.js` exists, but **there is no `example/` folder**
- `webpack example bundle.js`
- :arrow_right: WebPack throws this error:

`ERROR in Entry module not found: Error: Cannot resolve module 'example' in /path/this/test/was/launched/in`
### Expected behavior:

a) WebPack correctly resolves the path and starts compiling.
b) WebPack throws an error in both cases and doesn't compile anything
### Simple Steps To Reproduce
1. place this `package.json` in an empty folder

``` json
{
    "scripts": {
        "a": "mkdir a && touch a.js && webpack a bundle-a.js",
        "b": "touch b.js && webpack b bundle-b.js"
    },
    "dependencies": {
        "webpack": "^2.7.0"
    }
}
```

2, `npm i`
3. `npm run a`
4. `npm run b`

---

## Meta

Original issue: #2656, was closed due to inactivity, but it's still relevant.

### PR DESCRIPTION
**Pull request by gyandeeps**
**What kind of change does this PR introduce?**

Bugfix for #5576

**Did you add tests for your changes?**

Still try to figure out on how to test this.

**If relevant, link to documentation update:**

**Summary**

**Does this PR introduce a breaking change?**

**Other information**

### CODE REVIEW

File: bin/convert-argv.js [hunk 1]
```diff
@@ -537,7 +537,7 @@ module.exports = function(yargs, argv, convertOptions) {
 				if(i < 0 || (j >= 0 && j < i)) {
 					var resolved = path.resolve(content);
 					if(fs.existsSync(resolved)) {
-						addTo("main", resolved);
+						addTo("main", `${resolved}${path.extname(resolved) ? "" : path.sep}`);
```
Comment (sokra) [inline bin/convert-argv.js]: Please check if it's a folder with `fs.statsSync` `isDirectory`. Try to replace the `fs.existsSync` call, it's deprecated anyway.

**Comment by sokra** [comment]
Thanks
