### PR TITLE
flag all modules as used for Dll

### LINKED ISSUE #10189: undefined export when compiling vendors with DllPlugin mode production
# Bug report

**What is the current behavior?**
Compiling a simple React App using DLLPlugin with the `@reach/dialog` package included fails to initialize. Project compiles fine, but crashes at runtime with error:
```
TypeError: undefined is not an object (evaluating 'e[r].call')
```
Project runs fine when building in non production mode. (`--mode development`)
Project runs fine when excluding `@reach/dialog` from the Dll bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is a minimal project to replicate the issue https://glitch.com/edit/#!/reach-webpack-bug

**What is the expected behavior?**
Same behaviour as in ` --mode development`.
App boots fine with no error when bootstrapping the application.

**Other relevant information:**
webpack version:  webpack 4.41.5, webpack-cli 3.3.10
Node.js version: 10.16.3
Operating System: MacOS
Additional tools: include the `@reach/dialog` package in the project.

### LINKED ISSUE #10475: Missing module error in tree-shaked dll modules
# Bug report

**What is the current behavior?**

A module is missing in the dll chunk causing an error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (dll.js:21)
    at Module../test-package/index.js (dll.js:121)
    at __webpack_require__ (dll.js:21)
    at Module../dll.js (dll.js:95)
    at __webpack_require__ (dll.js:21)
    at Object.<anonymous> (index.js:107)
    at __webpack_require__ (index.js:20)
    at Module.<anonymous> (index.js:100)
    at __webpack_require__ (index.js:20)
    at Object.<anonymous> (index.js:91)
```

A library needs to re-export one of it's module in two steps like `constants` below to get this bug:
```js
// index.js of 'test-package'
import * as _constants from './constants';
export var constants = _constants;
export { default as someOtherFunction } from './someOtherFunction';
```

Then if you try to import `import { constants } from 'test-package'` in your dll. The end chunk will have a reference to the module `./someOtherFunction` but it won't actually be in the chunk causing the above error.

This only happens in a DLL

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/skimi/webpack-dll-bug

**What is the expected behavior?**

Missing module reference either completely removed because it can totally be tree-shaked or it can't at all and it should be kept in the chunk.

**Other relevant information:**

I got this error while using the redux-form library that has this kind of export.
Related issue at redux-form https://github.com/redux-form/redux-form/issues/4618

### PR DESCRIPTION
**Pull request by sokra**
fix problem that modules were removed before they were flagged as used

fixes #10189

backport of #10205

fixes #10475

**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
yes, dlls might be larger

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/working-constants.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+export const constant1 = 'constant1';
```
Comment (skimi) [inline test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/working-constants.js]: This file is not actually used

Comment (sokra) [reply test/configCases/dll-plugin/0-issue-10475/node_modules/test-package/working-constants.js]: It doesn't hurt...
