### PR TITLE
fix(nmf): Fix exports for var injection to include free glob export or args

### LINKED ISSUE #3917: 2.2.0-rc.4's es6 modules' "module" usage detection seems to be broken
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

External modules (symbol-observable, moment) no longer compile with this release.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use webpack 2.2.0-rc.4
2. Compile a script that requires moment or symbol-observable (or another module that triggers this problem)

**What is the expected behavior?**

Bundle compiles fine

---

It doesn't appear that moment and symbol-observable modules actually use `module.exports` at the locations Webpack says there is an error.

For example, `symbol-observable/es/index.js`:

```js
/* global window */
import ponyfill from './ponyfill';

var root;

if (typeof self !== 'undefined') {
  root = self;
} else if (typeof window !== 'undefined') {
  root = window;
} else if (typeof global !== 'undefined') {
  root = global;
} else if (typeof module !== 'undefined') {
  root = module;
} else {
  root = Function('return this')();
}

var result = ponyfill(root);
export default result;
```

Gives the error:

```
./~/symbol-observable/es/index.js
13:9-15 module is not allowed in EcmaScript module: This module was detected as EcmaScript module (import or export syntax was used). In such a module using 'module' is not allowed.
```

### PR DESCRIPTION
**Pull request by TheLarkInn**
**What kind of change does this PR introduce?**
Bugfix.

**Did you add tests for your changes?**
N/A

**If relevant, link to documentation update:**
N/A

**Summary**
Patches issue discovered in RC5. exportArguments should be tried first before "exports".

**Does this PR introduce a breaking change?**
No

**Other information**
Fixes #3917

### CODE REVIEW

**Comment by TheLarkInn** [comment]
Also fixed #3974

File: lib/NormalModule.js [hunk 1]
```diff
@@ -270,10 +270,9 @@ NormalModule.prototype.source = function(dependencyTemplates, outputOptions, req
 
 			var emitFunction = function emitFunction() {
 				if(varNames.length === 0) return;
-
 				varStartCode += "/* WEBPACK VAR INJECTION */(function(" + varNames.join(", ") + ") {";
 				// exports === this in the topLevelBlock, but exports do compress better...
-				varEndCode = (topLevelBlock === block ? "}.call(exports, " : "}.call(this, ") +
+				varEndCode = (topLevelBlock === block ? "}.call(module.exportsArgument || 'exports', " : "}.call(this, ") +
```
Comment (daltones) [inline lib/NormalModule.js]: ```'exports'``` string? Is that right? Sorry if that's intentional.
