### PR TITLE
fix: add missing public path in importScripts

### LINKED ISSUE #7529: Dynamic import not working on target: 'webworker' with custom output.publicPath
# Bug report

**What is the current behavior?**
When I use a dynamic import and I've setup `target: 'webworker'` on my webpack config, and I setup a custom `output.publicPath`, that path is not being set in that require, so file is not found when executing the code.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Create any proyect using webpack
* Setup `target: 'webworker'` on your webpack config's main level
* Setup your `output.publicPath` to a custom directory (different than root)
* On your `index.js` import a file on the following way `import(/* webpackChunkName: "my-module" */ 'my-module');` 
* Build/launch your app and open network inspector
* Look for a 404 error, looking for any bundle, and verify it's trying to be imported from `localhost:xxxx/chunkname-without-path.ext`

**What is the expected behavior?**
It's expected to inject the output path before the chunkname, so it's properly found.

I think that `mainTemplate.outputOptions.chunkFilename` in https://github.com/webpack/webpack/blob/510b68a828d4fa07dd889638c25f251cf1d84cc0/lib/webworker/WebWorkerMainTemplatePlugin.js#L39 comes without `path`

**Other relevant information:**
webpack version:  4.8.3
Node.js version: 8.9.1
Operating System: ElementaryOS 0.4.1 Loki (64 bits)
Additional tools:

### PR DESCRIPTION
**Pull request by scarletsky**
fixes #7529, fixes #8562

In #8562, the changes made by @prateekbh seems don't work any more, as the webpack repository does not contain `lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js`.

For more detail, here is the config:

```js
module.exports = {
    // ...
    output: {
        path: path.resolve(__dirname, '../public'),
        publicPath: '/',
        filename: 'static/scripts/[name].js',
    },
   // ...
}
```

After webpack bundling, it will output the following snippet:

```js
__webpack_require__.e = function requireEnsure(chunkId) {
    var promises = [];
    promises.push(Promise.resolve().then(function() {
        // "1" is the signal for "already loaded"
        if(!installedChunks[chunkId]) {
            importScripts("static/scripts/" + ({}[chunkId]||chunkId) + ".worker.js");
        }
    }));
    return Promise.all(promises);
};
```

Without public path, the browser will fetch a wrong path: `http://localhost:8000/static/scripts/static/scripts/5.worker.js`, which will cause 404 error.

**What kind of change does this PR introduce?**

a bugfix

**Did you add tests for your changes?**

Currently no tests.

**Does this PR introduce a breaking change?**

No.

**What needs to be documented once your changes are merged?**

Nothing.

### CODE REVIEW

File: lib/webworker/WebWorkerMainTemplatePlugin.js [hunk 1]
```diff
@@ -45,6 +45,9 @@ class WebWorkerMainTemplatePlugin {
 						"if(!installedChunks[chunkId]) {",
 						Template.indent([
 							"importScripts(" +
+								`"` +
+								mainTemplate.getPublicPath({ hash }) +
```
Comment (sokra) [inline lib/webworker/WebWorkerMainTemplatePlugin.js]: Use `__webpack_require__.p` instead. It's a runtime variable where the publicPath is stored.

Comment (scarletsky) [reply lib/webworker/WebWorkerMainTemplatePlugin.js]: Updated.

File: lib/webworker/WebWorkerMainTemplatePlugin.js [hunk 2]
```diff
@@ -45,6 +45,7 @@ class WebWorkerMainTemplatePlugin {
 						"if(!installedChunks[chunkId]) {",
 						Template.indent([
 							"importScripts(" +
+								`__webpack_require__.p + ` +
```
Comment (sokra) [inline lib/webworker/WebWorkerMainTemplatePlugin.js]:
```suggestion
								"__webpack_require__.p + " +
```

Comment (scarletsky) [reply lib/webworker/WebWorkerMainTemplatePlugin.js]: Updated.

**Comment by sokra** [comment]
Thanks
