### PR TITLE
keep hmr update with output.clean=true

### LINKED ISSUE #15206: HMR not working on webpack 5.66.0
# Bug report

**What is the current behavior?**
Hot module reloading is not working after updating webpack to v5.66.0.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Clone https://github.com/saltire/react-node-boilerplate.
- Run `npm i webpack@latest` to update to **5.66.0**.
- Run `npm run watch`.
- Modify `src/App.jsx`. The browser console reports `bundle rebuilding` twice, the request to `main.xxxxx.hot-update.json` fails with status 404, and the app does not update.

Notice the issue does not occur if webpack **5.65.0** is installed.

**What is the expected behavior?**
When making a change to a jsx file, the app should reload automatically.

**Other relevant information:**
webpack version:  5.66.0
Node.js version: 16
Operating System: MacOS
Additional tools

This repo uses `webpack-dev-middleware`, `webpack-hot-middleware`, `react-refresh`, and `@pmmmwh/react-refresh-webpack-plugin`, among other packages. The issue may stem from a conflict with one of these, but I don't have enough internal knowledge of webpack or these packages to say which. It could also be a misconfiguration on my part. I'm filing the issue with `webpack` because I was able to isolate the problem to an update of this package.

Let me know if you need any more info!

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

fixes #15206 

**Did you add tests for your changes?**

yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/CleanPlugin.js [hunk 1]
```diff
@@ -161,6 +180,7 @@ const applyDiff = (fs, outputPath, dry, logger, diff, isKept, callback) => {
 			switch (type) {
 				case "check":
 					if (isKept(filename)) {
+						keptAssets.set(filename, Date.now());
```
Comment (sokra) [inline lib/CleanPlugin.js:183]:
```suggestion
						keptAssets.set(filename, 0);
```

File: lib/CleanPlugin.js [hunk 2]
```diff
@@ -335,7 +361,12 @@ class CleanPlugin {
 						);
 					} while (newNormalizedAsset !== normalizedAsset);
 					if (normalizedAsset.startsWith("../")) continue;
-					currentAssets.add(normalizedAsset);
+					const assetInfo = compilation.assetsInfo.get(asset);
+					if (assetInfo && assetInfo.hotModuleReplacement) {
+						currentAssets.set(normalizedAsset, now + _10sec);
+					} else {
+						currentAssets.set(normalizedAsset, now);
```
Comment (sokra) [inline lib/CleanPlugin.js:368]:
```suggestion
						currentAssets.set(normalizedAsset, 0);
```

Comment (sokra) [reply lib/CleanPlugin.js:368]: Let's use `0` as timestamp for all non-time-bound entries.

File: lib/CleanPlugin.js [hunk 3]
```diff
@@ -346,19 +377,34 @@ class CleanPlugin {
...
-						} else {
-							oldAssets = currentAssets;
+					applyDiff(
+						fs,
+						outputPath,
+						dry,
+						logger,
+						diff,
+						isKept,
+						(err, notDeletedAssets) => {
```
Comment (sokra) [inline lib/CleanPlugin.js:397]:
```suggestion
						(err, keptAssets) => {
```

File: lib/CleanPlugin.js [hunk 4]
```diff
@@ -346,19 +377,34 @@ class CleanPlugin {
...
+							if (err) {
+								oldAssets = undefined;
+							} else {
+								if (oldAssets) mergeAssets(currentAssets, oldAssets);
+								oldAssets = currentAssets;
+								if (notDeletedAssets) mergeAssets(oldAssets, notDeletedAssets);
```
Comment (sokra) [inline lib/CleanPlugin.js:403]:
```suggestion
								if (keptAssets) mergeAssets(oldAssets, keptAssets);
```

**Review by sokra — CHANGES_REQUESTED** [review]
