### PR TITLE
[ImportParserPlugin] fix return value when creating context for `import()`

### LINKED ISSUE #8293: DefinePlugin regression
# Bug report

**What is the current behavior?**

DefinePlugin does not replace things in all situations.
I encounter this issue while upgrading from webpack v3.6.0 to v4.23.1

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
new webpack.DefinePlugin({
	NAME: 'foobar'
})
```
then:
```js
import(`./${NAME}.yaml`)
```

expands to:

```js
__webpack_require__("../mytest lazy recursive ^\\.\\/.*\\.yaml$")('./' + NAME + '.yaml')
```

that is not correct.

**Other relevant information:**
webpack version:  4.23.1
Node.js version: 10.10
Operating System: win7
Additional tools:

### PR DESCRIPTION
**Pull request by ljqx**
This PR fixes #8293 . Now `ImportParserPlugin` returns `true` when creating context, which stops parser walking on param of `import()`, then `DefinePlugin` fails to change value of it.

**What kind of change does this PR introduce?**
a bugfix

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/dependencies/ImportParserPlugin.js [hunk 1]
```diff
@@ -254,7 +254,7 @@ class ImportParserPlugin {
 				dep.loc = expr.loc;
 				dep.optional = !!parser.scope.inTry;
 				parser.state.current.addDependency(dep);
-				return true;
+				return false;
```
Comment (sokra) [inline lib/dependencies/ImportParserPlugin.js]: I think walking the full expression is not correct as it would handle constant pieces twice.

like this one: ``import(`./${CONSTANT}/${DEFINED_EXPRESSION}`)``

with `DefinePlugin({ CONSTANT: JSON.stringify("folder"), DEFINED_EXPRESSION: "foobar" })`

Could you add this to the test?

Comment (ljqx) [reply lib/dependencies/ImportParserPlugin.js]: Sadly you are right. Seems only reliable way to fix this is to walk necessary expressions in `ContextDependencyHelpers`. I'll push a new iteration

File: lib/dependencies/AMDDefineDependencyParserPlugin.js [hunk 2]
```diff
@@ -98,12 +105,14 @@ class AMDDefineDependencyParserPlugin {
 			return true;
 		}
 	}
-	processItem(parser, expr, param, namedModule) {
+	processItem(parser, expr, param, paramExpr, namedModule) {
 		if (param.isConditional()) {
-			param.options.forEach(param => {
-				const result = this.processItem(parser, expr, param);
+			param.options.forEach((param, idx) => {
```
Comment (sokra) [inline lib/dependencies/AMDDefineDependencyParserPlugin.js]: We need some tests for this.

I think this fails if multiple `?:` operators are nested. In this case `options` has more than 2 elements:

``` js
import(a ?
  (b ? "x" : `./${CONST_PREFIX}/${DEFINED_EXPRESSION}/${CONST_SUFFIX}`) :
  (c ? `./${CONST_PREFIX}/${DEFINED_EXPRESSION}/${CONST_SUFFIX}` : "y")
)
```

I think it make sense to add the expression tracking to the `BasicEvaluatedExpression` (i. e. `setExpression` for the whole thing, and `setTemplateString(quasis, parts)` for template strings), instead of reimplementing it here.

* You can call `setExpression` in `Parser.evaluateExpression` to do it once for all
* You need to change `getSimplifiedTemplateResult` in `Parser` a bit to get all the expressions too.
* `BasicEvaluatedExpression.setTemplateString` now takes `quasis` which is still the same, `parts` which are all the quasis and epxressions as `BasicEvaluatedExpression`s, so all the parts of the template string.

File: lib/dependencies/ContextDependencyHelpers.js [hunk 3]
```diff
@@ -45,7 +45,9 @@ ContextDependencyHelpers.create = (
 	Dep,
 	range,
 	param,
+	paramExpr,
```
Comment (sokra) [inline lib/dependencies/ContextDependencyHelpers.js]: You no longer need this argument, as `param` now contains this information.

File: lib/dependencies/ContextDependencyHelpers.js [hunk 4]
```diff
@@ -84,7 +86,17 @@ ContextDependencyHelpers.create = (
 		);
 		dep.loc = expr.loc;
 		const replaces = [];
-		if (prefixRange && prefix !== prefixRaw) {
+		const templateLiteral =
```
Comment (sokra) [inline lib/dependencies/ContextDependencyHelpers.js]: You can walk all `parts` of the `param`.

* If it's a constant string: replace the `range` with the string (push to `replaces`)
* If it's not constant: walk it with the parser

File: lib/dependencies/RequireResolveDependencyParserPlugin.js [hunk 5]
```diff
@@ -21,20 +21,24 @@ class RequireResolveDependencyParserPlugin {
 			if (expr.arguments.length !== 1) return;
 			const param = parser.evaluateExpression(expr.arguments[0]);
 			if (param.isConditional()) {
-				for (const option of param.options) {
+				param.options.forEach((option, idx) => {
```
Comment (sokra) [inline lib/dependencies/RequireResolveDependencyParserPlugin.js]: All these changes can be reverted as the expression is now tracked in the `BasicEvaluatedExpression`.

File: lib/dependencies/ContextDependencyHelpers.js [hunk 6]
```diff
@@ -45,7 +45,9 @@ ContextDependencyHelpers.create = (
 	Dep,
 	range,
 	param,
+	paramExpr,
 	expr,
+	parser,
```
Comment (sokra) [inline lib/dependencies/ContextDependencyHelpers.js]: To avoid a breaking change, make this argument optional. In this case expressions are not walked.

File: lib/dependencies/ContextDependencyHelpers.js [hunk 7]
```diff
@@ -84,7 +86,17 @@ ContextDependencyHelpers.create = (
...
+		templateLiteral.expressions.forEach(e => {
+			// expressions in postfix are needed to be walked
+			if (e.range[0] > prefixRange[1]) {
+				parser.walkExpression(e);
+			}
+		});
+		if (prefix !== prefixRaw) {
 			replaces.push({
 				range: prefixRange,
 				value: prefix
```
Comment (sokra) [inline lib/dependencies/ContextDependencyHelpers.js]: Lower in this file, at the `else` case, you need to walk the whole expression.

File: lib/dependencies/AMDDefineDependencyParserPlugin.js (hunk 2 above)
Comment (ljqx) [reply lib/dependencies/AMDDefineDependencyParserPlugin.js]: Thanks! I've thought it's too heavy for this PR, but surely it's more appropriate for easily tracking back the expr from `BasicEvaluatedExpression`

File: lib/dependencies/ContextDependencyHelpers.js (hunk 6 above)
Comment (ljqx) [reply lib/dependencies/ContextDependencyHelpers.js]: OK, thanks! Then in this PR I'll only handle `import()` case, then later working on AMD `define`, `require`, CommonJS `require` and `require.resolve`

**Comment by ljqx** [comment]
@sokra , I've published a new iteration. It's more readable now. Thanks!

**Comment by sokra** [comment]
Thanks
