### PR TITLE
disallow shorthand cache groups syntax with cache group named test

### LINKED ISSUE #9722: unknown filename with some different configuration in optimization.splitChunks
# Bug report
> The configuration of optimization.splitChunks  is 
```
optimization: {
        usedExports:true,
        splitChunks: {
            chunks: "all",
            cacheGroups: {
                test:/[\\/]node_modules[\\/]/,
            }
        }
    },
```

**What is the current behavior?**
It works and bundle the chunk with the name "test~lodash.chunk.js"

**If the current behavior is a bug, please provide the steps to reproduce.**

The office website about SplitChunksPlugin tells us that "splitChunks.cacheGroups.{cacheGroup}.test" controls which modules are selected by this cache group. It only chooses modules but not defines the name of chunk

**What is the expected behavior?**
If the code with such configuration should bundle the chunk with the name "vendors~lodash.chunk.js"

**Other relevant information:**
webpack version:  4.31.0
Node.js version: v10.15.1
Operating System: Mac OS 10.14.6
Additional tools:

### PR DESCRIPTION
**Pull request by sokra**
This is a potential config error

fixes #9722

**What kind of change does this PR introduce?**
validation

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
yes, but only when a user made a potential config error

**What needs to be documented once your changes are merged?**
nothing

### CODE REVIEW

File: lib/WebpackOptionsValidationError.js [hunk 1]
```diff
@@ -362,6 +362,10 @@ class WebpackOptionsValidationError extends WebpackError {
 					err.parentSchema
 				)}`;
 			}
+		} else if (err.keyword === "not") {
+			return `${dataPath} should not be ${getSchemaPartText(
+				err.schema
+			)}\n${getSchemaPartText(err.parentSchema)}`;
```
Comment (evilebottnawi) [inline lib/WebpackOptionsValidationError.js]: We should port this in `schema-utils`, right not is not implemented

Comment (sokra) [reply lib/WebpackOptionsValidationError.js]: yep
