### PR TITLE
fix bug for maxCallStack in ContextModuleFactory

### LINKED ISSUE #11378: [Webpack 5] ContextModuleFactory - RangeError: Maximum call stack size exceeded
# Bug report

**What is the current behavior?**

The software crashes with stack overflow.

**If the current behavior is a bug, please provide the steps to reproduce.**

```sh
git clone https://github.com/petermetz/blockchain-integration-framework.git
cd blockchain-integration-framework
git checkout -b build/webpack-optimization-139
npm i
./node_modules/.bin/webpack --env-csv=dev --target-csv=node

# To observe the effective webpack config that was returned by the config file 
# (which has an entry point and TS-loader rule per each package sub-directory)
# You can check out the contents of the webpack.config.json file =>
cat webpack.config.json
```

Observe the crash:

```sh

$$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:352
                                                        if (item) flattenedResult.push(...item);
                                                                                  ^
RangeError: Maximum call stack size exceeded
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:352:34
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)
    at $$PROJECT_ROOT$$/node_modules/webpack/lib/ContextModuleFactory.js:355:7
    at done ($$PROJECT_ROOT$$/node_modules/webpack/node_modules/neo-async/async.js:2931:13)

```

**What is the expected behavior?**

There is no stack overflow crash.

**Other relevant information:**
webpack version: `5.0.0-beta.28`  
Node.js version: `v12.16.3`
Operating System: `Ubuntu 20.04`
Additional tools: ts-loader

It's a mono-repo written in Typescript with packages being in sub-folders and some of them are dependent on others. I'm trying to have a separate bundle for each package and that's why I need Webpack 5 for the new, cool `dependOn` feature of the entry point object literal syntax. All the webpack config does is get a list of the packages in the mono-repo and their dependency graph, then transforms that into the webpack entry points and a list of ts-loader rules to use (one rule per package, specified via the `include` property of the rule).

### PR DESCRIPTION
**Pull request by Adityaperiwal**
What existing problem does the pull request solve?
max call stack error when resolving dependencies
Resolves #11378 [Webpack 5] ContextModuleFactory - RangeError: Maximum call stack size exceeded
**What kind of change does this PR introduce?**
Bugfix

**Did you add tests for your changes?**
Yes

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
None

### CODE REVIEW

File: lib/ContextModuleFactory.js [hunk 1]
```diff
@@ -275,9 +276,14 @@ module.exports = class ContextModuleFactory extends ModuleFactory {
 			category
 		} = options;
 		if (!regExp || !resource) return callback(null, []);
-
+		let visited = new Set();
 		const addDirectory = (directory, callback) => {
+			const realPath = path.resolve(directory);
```
Comment (evilebottnawi) [inline lib/ContextModuleFactory.js:281]: Why we need `resolve` this? We already known `context`, so you can add `path.join(context, directory)`

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:281]: do you mean `const realPath = path.join(resource, directory)` ? as I don't think we're directly passing `context` here.

Comment (evilebottnawi) [reply lib/ContextModuleFactory.js:281]: We know context of request, so we can just join them

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:281]: But context is undefined here, can you help me figure on how to extract the context?, Is context the resource property of options here?.

Comment (evilebottnawi) [reply lib/ContextModuleFactory.js:281]: Maybe this https://github.com/webpack/webpack/blob/d5d7f3d57692fe4455c85789ae1b1a3479bb89a4/lib/ContextModuleFactory.js#L316 or https://github.com/webpack/webpack/blob/d5d7f3d57692fe4455c85789ae1b1a3479bb89a4/lib/ContextModuleFactory.js#L87, need test

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:281]: The first one is what I believe it is.

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:281]: Resource contains the directory itself that we call at the end `addDirectory(resource, callback)`

Comment (sokra) [reply lib/ContextModuleFactory.js:281]: You want `fs.realpath` like in your first commit. It was in the right direction, but async logic was handled incorrectly.

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:281]: Actually realpath is optional property of File System so many tests were failing with `fs.realpath` is not a function.

Comment (evilebottnawi) [reply lib/ContextModuleFactory.js:281]: Can you put here test case? I will help

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:281]: Ok, let me try with fs.realpath optionally, if it doesn't exist, it means symlinks are not supported and there's no need for visited logic there. I'll put any test that is failing then.

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js]: Yes, no tests are failing now.

File: lib/ContextModuleFactory.js [hunk 2]
```diff
@@ -276,7 +276,26 @@ module.exports = class ContextModuleFactory extends ModuleFactory {
...
-		const addDirectory = (directory, callback) => {
+		const addDirectoryChecked = (directory, visited, callback) => {
+			fs.realpath(directory, (err, realPath) => {
+				if (err) return callback(err);
+				if (visited.has(realPath)) return callback(null, []);
+				let nestedVisited;
+				addDirectory(
+					directory,
+					(dir, callback) => {
+						if (nestedVisited === undefined) {
```
Comment (Adityaperiwal) [inline lib/ContextModuleFactory.js:287]: wouldn't `nestedVisited ` always be `undefined` here?.

Comment (Adityaperiwal) [reply lib/ContextModuleFactory.js:287]: @sokra  it looks like it resolves  this case right, otherwise it'll just mark C as visited at the very first 
 ```
A
|
B
| \
N  C
|
C 
```

**Comment by Adityaperiwal** [comment]
Hii @sokra  / @evilebottnawi  I've added the tests, but I wonder why `codecov/changes` is failing, Do I need to add more?.

**Comment by evilebottnawi** [comment]
@Adityaperiwal All good, don't worry

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
