### PR TITLE
fixes #8874

### LINKED ISSUE #8874: Scope is incorrectly determined when using function expressions.
# Bug report

**What is the current behavior?**
The imported function `someFunction` in `index.js` is incorrectly called from within the inline function expression `someFunction` in `index.js` instead of calling itself recursively.

**If the current behavior is a bug, please provide the steps to reproduce.**
Gist:
https://gist.github.com/MathijsMeijer/660d19a5eaccb819a5c3ccb12b2e9323

Structure:
`wp.js` 
`src/index.js`
`src/someFunction.js`

Run `npm i webpack` and `node wp.js`.

**What is the expected behavior?**
The inline function expression `someFunction` in `index.js` should call itself recursively. The imported function `someFunction` should _not_ be called.

**Other relevant information:**
webpack version: 4.29.6 / 5.0.0-alpha.11
Node.js version: 10.15.0
Operating System: MacOS 10.14.3
Additional tools: n/a

### PR DESCRIPTION
**Pull request by noelebrun**
**What kind of change does this PR introduce?**
Bugfix #8874 

**Did you add tests for your changes?**
Yes

**Does this PR introduce a breaking change?**
No

**What needs to be documented once your changes are merged?**
Nothing

### CODE REVIEW

**Comment by noelebrun** [comment]
@sokra I pushed a commit with the wrong email, forced pushed with the right email after creating the PR but the CLA check doesn't seems to take this into account. Do I have to close this one and create a new one to make it pass?

File: lib/Parser.js [hunk 1]
```diff
@@ -1777,7 +1777,14 @@ class Parser extends Tapable {
 		const args = options.map(renameArgOrThis);
 		const wasTopLevel = this.scope.topLevelScope;
 		this.scope.topLevelScope = false;
-		this.inScope(params.filter((identifier, idx) => !args[idx]), () => {
+		const scopeParams = params.filter((identifier, idx) => !args[idx]);
+
+		// Add function name in scope for recursive calls
+		if (functionExpression.id) {
+			scopeParams.push(functionExpression.id.name);
```
Comment (sokra) [inline lib/Parser.js]: I think this need to be `unshift` instead to catch this case:

```js
(function someFn(arg = someFn) {
```

Comment (noelebrun) [reply lib/Parser.js]: Just wrote a new test case for this situation with the default parameter and it seems to work as expected. Could you detail in which case it would not work?

**Comment by mvanbutselaar** [comment]
Could we also add this fix for the normal (non IF) Function Expression? Or should we create a new issue / pull request for this.

I have made a pull request on @noelebrun bugfix branch to add a fix and tests for this, just in case.

**Comment by evilebottnawi** [comment]
@mvanbutselaar better send a new PR

**Comment by noelebrun** [comment]
I already merged the PR, is that fine?

File: lib/Parser.js (hunk 1 above)
Comment (sokra) [reply lib/Parser.js]: ok great

**Comment by sokra** [comment]
@mvanbutselaar please also sign the CLA

**Comment by mvanbutselaar** [comment]
Signed the CLA.

**Comment by noelebrun** [comment]
@sokra The Azure DevOps pipeline coverage job seems to have timeout, any idea why?

**Comment by sokra** [comment]
Thanks
