### PR TITLE
import.meta.webpackContext

### LINKED ISSUE #15372: `require.context` not parsed in ESM packages
# Bug report

**What is the current behavior?**

In packages with `type: "module"`, webpack fails to parse and replace `require.context()` expressions.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone https://github.com/tavoyne/webpack-2ece8c.
2. Run `yarn webpack --mode=production`.
3. Inspect the `dist/main.js` file and notice that the `require.context()` expression is still present.
4. (Remove `type: "module"` from the `package.json` file.)
5. (Inspect the `dist/main.js` file again and notice how the `require.context()` expression was successfully replaced.)

**What is the expected behavior?**

The replacement to be successful at step (3).

As `require` is not available in ESM environments, it could be called `import.context` in order to avoid confusion.

**Other relevant information:**
webpack version:  `5.68.0`
Node.js version: `17.4.0`
Operating System: MacOS
Additional tools: N/A

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

feature 
closes #15372 

**Did you add tests for your changes?**
yes

**Does this PR introduce a breaking change?**
no

**What needs to be documented once your changes are merged?**
`import.meta.webpackContext("directory", { recursive: boolean, regExp: RegExp, mode })` returns same as `require.context` but only for `javascript/auto`, `javascript/esm`

### CODE REVIEW

File: lib/dependencies/ImportMetaContextDependencyParserPlugin.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+					break;
+				}
+				case "recursive": {
+					const recursiveExpr = parser.evaluateExpression(
+						/** @type {ExpressionNode} */ (prop.value)
+					);
+					if (!recursiveExpr.isBoolean()) return;
+					recursive = recursiveExpr.bool;
+				}
+			}
```
Comment (sokra) [inline lib/dependencies/ImportMetaContextDependencyParserPlugin.js:53]: We should throw an error for any unsupported or invalid property.

File: lib/dependencies/ImportMetaContextDependencyParserPlugin.js [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+ * @returns {{mode: string, recursive: boolean, regExp: RegExp}} options
+ */
+function getOptions(parser, optionsNode) {
+	let regExp = /^\.\/.*$/;
+	let recursive = true;
+	let mode = "sync";
+	if (optionsNode) {
+		for (const prop of optionsNode.properties) {
+			if (prop.type !== "Property" || prop.key.type !== "Identifier") return;
+			switch (prop.key.name) {
```
Comment (sokra) [inline lib/dependencies/ImportMetaContextDependencyParserPlugin.js:29]: There are a bunch of other options we want to support here:

* `chunkName`
* `include`
* `exclude`
* `prefetch`
* `preload`
* `exports`

File: lib/dependencies/ImportMetaContextDependencyParserPlugin.js [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+					break;
+				}
+				case "mode": {
+					const modeExpr = parser.evaluateExpression(
+						/** @type {ExpressionNode} */ (prop.value)
+					);
+					if (!modeExpr.isString()) return;
+					mode = modeExpr.string;
+					break;
+				}
```
Comment (sokra) [inline lib/dependencies/ImportMetaContextDependencyParserPlugin.js:45]: `mode` need to be handled directly during parsing in that plugin. It can't be passed to the dependency.

**Review by sokra — CHANGES_REQUESTED** [review]
Best see lib/dependencies/ImportParserPlugin.js how all these options need to be handled.

File: lib/dependencies/RequireContextPlugin.js [hunk 4]
```diff
@@ -50,6 +60,16 @@ class RequireContextPlugin {
 					new RequireContextDependencyParserPlugin().apply(parser);
 				};
 
+				const handlerImportMeta = (parser, parserOptions) => {
+					new ImportMetaContextDependencyParserPlugin().apply(parser);
```
Comment (sokra) [inline lib/dependencies/RequireContextPlugin.js:64]: We should also add a parser option to disable that behavior:

``` js
					if (
						parserOptions.importMetaContext !== undefined &&
						!parserOptions.importMetaContext
					)
						return;
```

File: lib/dependencies/RequireContextPlugin.js [hunk 5]
```diff
@@ -34,6 +36,14 @@ class RequireContextPlugin {
...
 					new RequireContextDependency.Template()
 				);
+				compilation.dependencyFactories.set(
+					ImportMetaContextDependency,
+					contextModuleFactory
+				);
+				compilation.dependencyTemplates.set(
+					ImportMetaContextDependency,
+					new ImportMetaContextDependency.Template()
+				);
```
Comment (sokra) [inline lib/dependencies/RequireContextPlugin.js:46]: `RequireContextPlugin.js` sounds a bit like the wrong plugin name.

Best split that into a separate `ImportMetaContextPlugin.js`

File: test/cases/chunks/context-weak/index.js [hunk 6]
```diff
@@ -1,18 +1,22 @@
 it("should not bundle context requires with asyncMode === 'weak'", function() {
```
Comment (sokra) [inline test/cases/chunks/context-weak/index.js:1]: copy that test case to keep the old require.context test too.

**Review by sokra — CHANGES_REQUESTED** [review]

File: lib/dependencies/ImportMetaContextDependency.js [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+		return `import.meta.webpackContext ${this.options.mode}`;
+	}
+}
+
+makeSerializable(
+	ImportMetaContextDependency,
+	"webpack/lib/dependencies/ImportMetaContextDependency"
+);
+
+ImportMetaContextDependency.Template = ModuleDependencyTemplateAsRequireId;
```
Comment (vankop) [inline lib/dependencies/ImportMetaContextDependency.js:33]: also is this correct one?

File: lib/dependencies/ImportMetaContextPlugin.js [hunk 8]
```diff
@@ -0,0 +1,59 @@
...
+					new ImportMetaContextDependency.Template()
+				);
+				compilation.dependencyFactories.set(
+					ContextElementDependency,
+					normalModuleFactory
+				);
+
+				const handler = (parser, parserOptions) => {
+					if (
+						parserOptions.importMetaContext !== undefined &&
```
Comment (sokra) [inline lib/dependencies/ImportMetaContextPlugin.js:40]: This option need to be added to the schema

**Review by sokra — APPROVED** [review]

**Comment by Tofandel** [comment]
There seems to be a bug when using it with a package

````js
  const locales = import.meta.webpackContext('@/locales', {
    recursive: false,
    regExp: /(en|hu)\.json$/i,
  });
  const vuetify = import.meta.webpackContext('vuetify/lib/locale', {
    recursive: false,
    regExp: /(en|hu)\.js$/i,
  });
```

First one works perfect, second one throws warning during compilation
```
 WARNING  Compiled with 2 warnings                                                                                                                                                                                             6:09:41 PM

 warning  in ./node_modules/vuetify/lib/locale/ ./node_modules/vuetify/lib/locale/ sync nonrecursive (en%7Chu)\.js$/

Module not found: Error: Can't resolve './node_modules/vuetify/lib/locale/vuetify/lib/locale/en.js' in '***'

 warning  in ./node_modules/vuetify/lib/locale/ ./node_modules/vuetify/lib/locale/ sync nonrecursive (en%7Chu)\.js$/

Module not found: Error: Can't resolve './node_modules/vuetify/lib/locale/vuetify/lib/locale/hu.js' in '***'

```

It seems to be using the context twice

**Comment by alexander-akait** [comment]
@Tofandel Looks like yes, please open an issue, thanks

**Comment by Tofandel** [comment]
Managed to get a minimal repro (funny enough only seems to happen with vue-cli) so will open one

**Comment by Tofandel** [comment]
Got it to reproduce without vue-cli

Just adding this in the webpack config
```
const path = require('path')
module.exports = {
  resolve: {
    modules: [
      'node_modules',
      path.resolve(__dirname, './node_modules'),
    ]
  },
}
```

**Comment by Tofandel** [comment]
Also, not really a bug, but just exploring this without a doc

I found that the default mode is `sync` and so if using `chunkName` without a `mode` it will have no effect, maybe we can change the default to 'lazy-once' if a chunkName is given?

```
const vuetify = import.meta.webpackContext('vuetify/lib/locale', {
  recursive: false,
  chunkName: 'locales', // This does nothing until we add mode: 'lazy'
  regExp: /(en|hu)\.js$/i,
});
```

**Comment by vankop** [comment]
> Also, not really a bug, but just exploring this without a doc
> 
> I found that the default mode is `sync` and so if using `chunkName` without a `mode` it will have no effect, maybe we can change the default to 'lazy-once' if a chunkName is given? Otherwise I'd add a compilation warning if chunkName is given with a mode that doesn't use the chunkName
> 
> ```
> const vuetify = import.meta.webpackContext('vuetify/lib/locale', {
>   recursive: false,
>   chunkName: 'locales', // This does nothing until we add mode: 'lazy' or mode: 'lazy-once'
>   regExp: /(en|hu)\.js$/i,
> });
> ```

yeah, need to add a warning if not `lazy*` mode
