### PR TITLE
Prefer chunks with entry module when picking name (#7516)

### LINKED ISSUE #7516: `Chunk.integrate()` can arbitrarily rename entry name chunk
# Bug report

I've a webpack config with a "server" entry whose chunk name is renamed with the name of a split chunk when using `LimitChunkCountPlugin`. Then `webpackHotServerMiddleware(compiler, { chunkName: 'server',  })` fails to retrieve the handler with given chunk name.

**What is the current behavior?**
webpackHotServerMiddleware, or anything that uses chunk names of chunk that reveived a call to  `Chunk.integrate()` might fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

See example repo: https://github.com/nicolas-cherel/WebpackNameChunkBug

**What is the expected behavior?**
The entry chunk name should not be renamed.

The following code might not need to override receiving chunk name into the otherChunk name. (given that callee respects chunks hierarchy in calls).

https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L380-L389

**Other relevant information:**
webpack version:  4.12.0
Node.js version: v8.10.0 // should be irrelevevant here
Operating System: macOS high Sierra
Additional tools: N/A

*edit: as discussed bellow you can mitigate the issue using long chunks name to avoid override of short chunk names you want to keep*

### PR DESCRIPTION
**Pull request by fabianishere**
This PR changes the behavior of `Chunk#integrate` to prefer chunks with an entry module when picking a name. If none have an entry module, the old algorithm is used instead, where the chunk with the shortest name is picked.

See #7516 for the bug report.

**What kind of change does this PR introduce?**
This change is a bugfix.

**Did you add tests for your changes?**
I could not find tests related to this change. Do you want me to add them?

**Does this PR introduce a breaking change?**
This PR introduces a breaking change by changing the behavior of `Chunk#integrate`. Projects, plugins and internal code relying on the fact that the shortest name is picked when integrating two chunks may break. However, I think more people are affected by the current behavior.

**What needs to be documented once your changes are merged?**
The behavior of `Chunk#integrate` with regards to naming might need to be documented to explain current behavior.

Fixes #7516

### CODE REVIEW

**Comment by fabianishere** [comment]
@sokra Shouldn't it be better to make the integration order deterministic/fixed instead? Or is that not feasible?

**Comment by fabianishere** [comment]
@sokra I have updated the branch to prefer chunks with an entry module. However, I suspect the algorithm might now still produce different results for a different order of integration.

File: lib/Chunk.js [hunk 1]
```diff
@@ -396,8 +396,12 @@ class Chunk {
 		}
 		otherChunk._groups.clear();
 
-		if (this.name && otherChunk.name) {
-			if (this.name.length !== otherChunk.name.length) {
+		// Pick a new name for the chunk; prefer chunks with an entry module
+		// Otherwise, choose chunk with shortest name
+		if (this.name && otherChunk.name && !this.entryModule) {
```
Comment (sokra) [inline lib/Chunk.js]: Also handle the case were both chunks have `entryModule`s

Comment (fabianishere) [reply lib/Chunk.js]: The first is picked at the moment. Do you want to fallback to shortest name then?

Comment (sokra) [reply lib/Chunk.js]: yep, need to be deteministic

**Comment by fabianishere** [comment]
c04747f17 fixes it already

**Comment by sokra** [comment]
It doesn't fix it

**Comment by fabianishere** [comment]
Oh, but I fear this approach does not work as from the logic in “Chunk#canBeIntegrated”, it looks like chunks with entry modules are prevented from integrating.

**Comment by sokra** [comment]
> it looks like chunks with entry modules are prevented from integrating.

They can be integrated in cases when it returns here:

https://github.com/webpack/webpack/blob/c74bee9cef6cd733ccf64037c3d3e010d4413082/lib/Chunk.js#L467

or here:

https://github.com/webpack/webpack/blob/c74bee9cef6cd733ccf64037c3d3e010d4413082/lib/Chunk.js#L469

**Comment by fabianishere** [comment]
Ah, I had not considered that. I will prepare some tests for the patch then (and rebase it to current ‘master’)

**Comment by sokra** [comment]
> I will prepare some tests for the patch then (and rebase it to current ‘master’)

no need. I already did that

**Comment by sokra** [comment]
Thanks
