### PR TITLE
use nonNumericOnlyHash function for contentHash

### LINKED ISSUE #15288: invalid key when chunks are formatted with non-zero only
### Discussed in https://github.com/webpack/webpack/discussions/15264

<div type='discussions-op-text'>

<sup>Originally posted by **aleen42** January 27, 2022</sup>

# Bug report

**What is the current behavior?**

Recently, I have found that when a chunk is not formatted with all numbers, it can't be loaded because of the undefined variable:

```js
/*! For license information please see 117.4b325.js.LICENSE.txt */
(self.webpackJsonp = self.webpackJsonp || []).push([[117], {
    11543: function(e, t, i) {
        var n = i(61493);
        i(f912e); // Throw error here
   },
   'f912e': function () {
   }
});
```

**Other relevant information:**
webpack version:  5.67.0
Node.js version: 17.3.1
Operating System: Windows OS
Additional tools:
</div>

### PR DESCRIPTION
**Pull request by vankop**
**What kind of change does this PR introduce?**

fixes #15288 

**Did you add tests for your changes?**

partial

**Does this PR introduce a breaking change?**

no

**What needs to be documented once your changes are merged?**

nothing

### CODE REVIEW

File: lib/util/nonNumericOnlyHash.js [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+/**
+ * @param {string} hash hash
+ * @param {number} hashLength hash length
+ * @returns {string} returns hash that has at least one non numeric char
+ */
+module.exports = (hash, hashLength) => {
+	if (hashLength < 1) return "";
+	const slice = hash.slice(0, hashLength);
+	if (slice.match(/[^\d]/)) return slice;
+	return `${String.fromCharCode(A_CODE + parseInt(hash[0], 10))}${slice.slice(
```
Comment (sokra) [inline lib/util/nonNumericOnlyHash.js:19]:
```suggestion
	return `${String.fromCharCode(A_CODE + (parseInt(hash[0], 10) % 6))}${slice.slice(
```

We want to make sure that is stays hex. Otherwise it might be a bit unexpected that `hashDigest="hex"` leads to chars out of the hex range

**Review by sokra — CHANGES_REQUESTED** [review]

**Review by sokra — APPROVED** [review]

**Comment by sokra** [comment]
Thanks
