### PR TITLE
avoid injection jsonpScriptSrc function when not needed

### LINKED ISSUE #7185: Contenthash doesn't work with splitchunks: 'all'
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Webpack throws a `Cannot convert undefined or null to object` error when `contenthash` is used for `output.filename` and `splitChunks.chunks: 'all' is enabled`.

screen shot 2018-05-03 at 14 33 44

This is the webpack.config, [link to reproducible repo](https://github.com/marcofugaro/webpack-issue-repo):

```js
  output: {
    filename: 'app.[contenthash:8].js',
    chunkFilename: '[name].[contenthash:8].chunk.js',
  },
  mode: 'production',
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: 'vendors',
    },
  },
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`git clone git@github.com:marcofugaro/webpack-issue-repo.git`
`yarn`
`yarn build`

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node v9.6.1 - webpack v4.6.0 - OSX

PS: I took the suggestion from a sokra comment from [this pr in create-react-app](https://github.com/facebook/create-react-app/pull/4077)
screen shot 2018-05-03 at 12 55 19

### PR DESCRIPTION
**Pull request by sokra**
**What kind of change does this PR introduce?**
bugfix

**Did you add tests for your changes?**
yes

**If relevant, link to documentation update:**
N/A

**Summary**
fixes #7185

**Does this PR introduce a breaking change?**
no

**Other information**

### CODE REVIEW

File: lib/web/JsonpMainTemplatePlugin.js [hunk 1]
```diff
@@ -130,12 +136,13 @@ class JsonpMainTemplatePlugin {
...
-						"}",
-						"",
-						needEntryDeferringCode(chunk) ? "var deferredModules = [];" : ""
+						"}"
 					]);
 				}
-				return source;
+				if (extraCode.length === 0) return source;
+				return Template.asString(
+					[source].concat(extraCode.map(Template.asString))
```
Comment (ooflorent) [inline lib/web/JsonpMainTemplatePlugin.js]: The following seems simpler:

```js
Template.asString([source, ...extraCode])
```

Comment (sokra) [reply lib/web/JsonpMainTemplatePlugin.js]: fixed

**Comment by montogeek** [comment]
20 bytes savings!
